package org.monogram.tools.tl.codegen.gradle

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.readBytes
import kotlin.io.path.writeBytes

class TlCodegenTaskApiTest {
    @Test
    fun `reports and generated bytes are deterministic`() {
        val fixture = fixture()
        val firstOutput = fixture.root.resolve("first")
        val secondOutput = fixture.root.resolve("second")
        val api = TlCodegenTaskApi(fixture.pipeline())

        val validation1 = api.validate(fixture.manifest).toDeterministicJson()
        val validation2 = api.validate(fixture.manifest).toDeterministicJson()
        val generation1 = api.generate(fixture.manifest, firstOutput).toDeterministicJson()
        val generation2 = api.generate(fixture.manifest, secondOutput).toDeterministicJson()
        val verification1 = api.verify(fixture.manifest, firstOutput).toDeterministicJson()
        val verification2 = api.verify(fixture.manifest, secondOutput).toDeterministicJson()

        assertEquals(validation1, validation2)
        assertEquals(generation1, generation2)
        assertEquals(verification1, verification2)
        assertEquals(fixture.outputs.keys.sorted(), outputFiles(firstOutput).keys.toList())
        fixture.outputs.forEach { (path, bytes) ->
            assertArrayEquals(bytes, firstOutput.resolve(path).readBytes())
            assertArrayEquals(bytes, secondOutput.resolve(path).readBytes())
        }
        assertFalse(validation1.contains(fixture.root.toString()))
        assertFalse(generation1.contains(fixture.root.toString()))
        assertFalse(generation1.contains("generatedAt"))
    }

    @Test
    fun `generation replaces output and removes stale files`() {
        val fixture = fixture()
        val output = fixture.root.resolve("generated").createDirectories()
        output.resolve("stale.kt").writeBytes("stale\n".toByteArray())
        output.resolve("old/tree.txt").also { it.parent.createDirectories() }
            .writeBytes("old\n".toByteArray())

        TlCodegenTaskApi(fixture.pipeline()).generate(fixture.manifest, output)

        assertEquals(fixture.outputs.keys.sorted(), outputFiles(output).keys.toList())
        assertFalse(Files.exists(output.resolve("stale.kt")))
        assertFalse(Files.exists(output.resolve("old")))
    }

    @Test
    fun `verification rejects changed missing and extra outputs without writing`() {
        val fixture = fixture()
        val api = TlCodegenTaskApi(fixture.pipeline())

        val changed = fixture.root.resolve("changed")
        api.generate(fixture.manifest, changed)
        changed.resolve("alpha.kt").writeBytes("changed\n".toByteArray())
        val changedBefore = outputFiles(changed)
        assertFailure(TlCodegenTaskFailure.OUTPUT_MISMATCH, "changed=alpha.kt") {
            api.verify(fixture.manifest, changed)
        }
        assertByteMapsEqual(changedBefore, outputFiles(changed))

        val missing = fixture.root.resolve("missing")
        api.generate(fixture.manifest, missing)
        Files.delete(missing.resolve("nested/beta.json"))
        assertFailure(TlCodegenTaskFailure.OUTPUT_MISMATCH, "missing=nested/beta.json") {
            api.verify(fixture.manifest, missing)
        }

        val extra = fixture.root.resolve("extra")
        api.generate(fixture.manifest, extra)
        extra.resolve("extra.txt").writeBytes("extra\n".toByteArray())
        assertFailure(TlCodegenTaskFailure.OUTPUT_MISMATCH, "extra=extra.txt") {
            api.verify(fixture.manifest, extra)
        }
    }

    @Test
    fun `generation rejects traversal and existing output symlinks`() {
        val fixture = fixture()
        val traversalPipeline = fixture.pipeline(
            mapOf("../escaped.kt" to "escaped\n".toByteArray(StandardCharsets.UTF_8)),
        )
        assertFailure(TlCodegenTaskFailure.UNSAFE_PATH, "invalid-output-path:../escaped.kt") {
            TlCodegenTaskApi(traversalPipeline).generate(fixture.manifest, fixture.root.resolve("traversal"))
        }
        assertFalse(Files.exists(fixture.root.resolve("escaped.kt")))

        val output = fixture.root.resolve("symlink-output").createDirectories()
        val target = fixture.root.resolve("outside.txt")
        target.writeBytes("outside\n".toByteArray())
        val link = output.resolve("linked.txt")
        try {
            Files.createSymbolicLink(link, target)
        } catch (_: Exception) {
            return
        }
        assertFailure(TlCodegenTaskFailure.UNSAFE_PATH, "symlink-in-output:linked.txt") {
            TlCodegenTaskApi(fixture.pipeline()).generate(fixture.manifest, output)
        }
        assertEquals("outside\n", Files.readString(target))
    }

    @Test
    fun `failed generation preserves previous output exactly`() {
        val fixture = fixture()
        val output = fixture.root.resolve("preserved").createDirectories()
        output.resolve("existing.txt").writeBytes("keep\n".toByteArray())
        val before = outputFiles(output)
        val failingPipeline = object : TlCodegenPipeline {
            override fun validate(manifestPath: Path): TlValidationSummary = fixture.validation

            override fun generate(manifestPath: Path): TlGeneratedCorpus {
                throw IllegalStateException("fixture generation failure")
            }
        }

        assertFailure(TlCodegenTaskFailure.GENERATION, "generator-failed:IllegalStateException") {
            TlCodegenTaskApi(failingPipeline).generate(fixture.manifest, output)
        }
        assertByteMapsEqual(before, outputFiles(output))
    }

    @Test
    fun `CLI uses stable operation exit codes`() {
        val fixture = fixture()
        val api = TlCodegenTaskApi(fixture.pipeline())
        val output = fixture.root.resolve("cli")
        val stdout = java.io.ByteArrayOutputStream()
        val stderr = java.io.ByteArrayOutputStream()

        assertEquals(
            TlCodegenTaskCli.EXIT_USAGE,
            TlCodegenTaskCli.run(emptyArray(), api, java.io.PrintStream(stdout), java.io.PrintStream(stderr)),
        )
        assertEquals(
            TlCodegenTaskCli.EXIT_SUCCESS,
            TlCodegenTaskCli.run(
                arrayOf("generate", fixture.manifest.toString(), output.toString()),
                api,
                java.io.PrintStream(stdout),
                java.io.PrintStream(stderr),
            ),
        )
        output.resolve("alpha.kt").writeBytes("different\n".toByteArray())
        assertEquals(
            TlCodegenTaskCli.EXIT_OUTPUT_MISMATCH,
            TlCodegenTaskCli.run(
                arrayOf("verify", fixture.manifest.toString(), output.toString()),
                api,
                java.io.PrintStream(stdout),
                java.io.PrintStream(stderr),
            ),
        )
    }

    private fun fixture(): Fixture {
        val root = Files.createTempDirectory("tl-task-api")
        val manifest = root.resolve("manifest.json")
        manifest.writeBytes("{}\n".toByteArray(StandardCharsets.UTF_8))
        return Fixture(
            root = root,
            manifest = manifest,
            validation = TlValidationSummary(
                listOf(
                    TlCodegenSchemaReport(
                        kind = "transport",
                        layer = null,
                        constructors = 2,
                        functions = 1,
                        sourceSha256 = "1".repeat(64),
                        snapshotSha256 = "2".repeat(64),
                    ),
                ),
            ),
            outputs = linkedMapOf(
                "nested/beta.json" to "{\n  \"ok\": true\n}\n".toByteArray(StandardCharsets.UTF_8),
                "alpha.kt" to "package fixture\n".toByteArray(StandardCharsets.UTF_8),
            ),
        )
    }

    private data class Fixture(
        val root: Path,
        val manifest: Path,
        val validation: TlValidationSummary,
        val outputs: Map<String, ByteArray>,
    ) {
        fun pipeline(generatedOutputs: Map<String, ByteArray> = outputs): TlCodegenPipeline =
            object : TlCodegenPipeline {
                override fun validate(manifestPath: Path): TlValidationSummary {
                    assertEquals(manifest, manifestPath)
                    return validation
                }

                override fun generate(manifestPath: Path): TlGeneratedCorpus {
                    assertEquals(manifest, manifestPath)
                    return TlGeneratedCorpus(validation, generatedOutputs)
                }
            }
    }

    private fun assertFailure(
        expectedFailure: TlCodegenTaskFailure,
        expectedDetail: String,
        block: () -> Unit,
    ) {
        val failure = try {
            block()
            throw AssertionError("Expected $expectedFailure")
        } catch (error: TlCodegenTaskException) {
            error
        }
        assertEquals(expectedFailure, failure.failure)
        assertTrue("Expected '${failure.detail}' to contain '$expectedDetail'", failure.detail.contains(expectedDetail))
    }

    private fun outputFiles(root: Path): Map<String, ByteArray> = Files.walk(root).use { paths ->
        paths.filter(Files::isRegularFile)
            .map { path -> root.relativize(path).toString().replace('\\', '/') to Files.readAllBytes(path) }
            .toList()
            .toMap()
            .toSortedMap()
    }

    private fun assertByteMapsEqual(expected: Map<String, ByteArray>, actual: Map<String, ByteArray>) {
        assertEquals(expected.keys, actual.keys)
        expected.forEach { (path, bytes) -> assertArrayEquals(path, bytes, actual.getValue(path)) }
    }
}
