package org.monogram.core.common.telegram

/**
 * Compact ingest of https://core.telegram.org/api/errors.json (layer 227).
 * Method lists are omitted; codes, patterns, and official descriptions are kept.
 * Regenerated from the official JSON; do not hand-edit rows.
 */
internal object TelegramErrorCatalog {
    const val LAYER: Int = 227
    const val SIZE: Int = 818
    val rows: Array<Row> = arrayOf(
        Row(-503, "MSG_WAIT_TIMEOUT", "Spent too much time waiting for a previous query in the invokeAfterMsg request queue, aborting!"),
        Row(-503, "Timeout", "Timeout while fetching data."),
        Row(303, "NETWORK_MIGRATE_%d", "Your IP address is associated to DC %d, please re-send the query to that DC."),
        Row(303, "PHONE_MIGRATE_%d", "Your phone number is associated to DC %d, please re-send the query to that DC."),
        Row(303, "STATS_MIGRATE_%d", "Channel statistics for the specified channel are stored on DC %d, please re-send the query to that DC."),
        Row(303, "USER_MIGRATE_%d", "Your account is associated to DC %d, please re-send the query to that DC."),
        Row(400, "ABOUT_TOO_LONG", "About string too long."),
        Row(400, "ACCESS_TOKEN_EXPIRED", "Access token expired."),
        Row(400, "ACCESS_TOKEN_INVALID", "Access token invalid."),
        Row(400, "ADDRESS_INVALID", "The specified geopoint address is invalid."),
        Row(400, "ADMINS_TOO_MUCH", "There are too many admins."),
        Row(400, "ADMIN_ID_INVALID", "The specified admin ID is invalid."),
        Row(400, "ADMIN_RANK_EMOJI_NOT_ALLOWED", "An admin rank cannot contain emojis."),
        Row(400, "ADMIN_RANK_INVALID", "The specified admin rank is invalid."),
        Row(400, "ADMIN_RIGHTS_EMPTY", "The chatAdminRights constructor passed in keyboardButtonRequestPeer.peer_type.user_admin_rights has no rights set (i.e. flags is 0)."),
        Row(400, "AD_EXPIRED", "The ad has expired (too old or not found)."),
        Row(400, "AICOMPOSE_FLOOD_PREMIUM", "You've reached the daily limit of AI text transformations, upgrade to [Telegram Premium](https://core.telegram.org/api/premium) to get **50x** times more AI text transformations per day!"),
        Row(400, "AICOMPOSE_TONE_INVALID", "The specified tone is invalid."),
        Row(400, "AICOMPOSE_TONE_TITLE_INVALID", "The specified tone title is invalid."),
        Row(400, "AI_COMPOSE_TASK_MISSING", "No AI task was specified. The caller must provide at least one of: proofread, translate (with a target language), tone, or emojify."),
        Row(400, "ALBUM_PHOTOS_TOO_MANY", "You have uploaded too many profile photos, delete some before retrying."),
        Row(400, "API_ID_INVALID", "API ID invalid."),
        Row(400, "API_ID_PUBLISHED_FLOOD", "This API id was published somewhere, you can't use it now."),
        Row(400, "ARTICLE_TITLE_EMPTY", "The title of the article is empty."),
        Row(400, "AUDIO_CONTENT_URL_EMPTY", "The remote URL specified in the content field is empty."),
        Row(400, "AUDIO_TITLE_EMPTY", "An empty audio title was provided."),
        Row(400, "AUTH_BYTES_INVALID", "The provided authorization is invalid."),
        Row(400, "AUTH_TOKEN_ALREADY_ACCEPTED", "The specified auth token was already accepted."),
        Row(400, "AUTH_TOKEN_EXCEPTION", "An error occurred while importing the auth token."),
        Row(400, "AUTH_TOKEN_EXPIRED", "The authorization token has expired."),
        Row(400, "AUTH_TOKEN_INVALID", "The specified auth token is invalid."),
        Row(400, "AUTH_TOKEN_INVALIDX", "The specified auth token is invalid."),
        Row(400, "AUTOARCHIVE_NOT_AVAILABLE", "The autoarchive setting is not available at this time: please check the value of the [autoarchive_setting_available field in client config &raquo;](https://core.telegram.org/api/config#client-configuration) before calling this method."),
        Row(400, "BALANCE_TOO_LOW", "The transaction cannot be completed because the current [Telegram Stars balance](https://core.telegram.org/api/stars) is too low."),
        Row(400, "BANK_CARD_NUMBER_INVALID", "The specified card number is invalid."),
        Row(400, "BANNED_RIGHTS_INVALID", "You provided some invalid flags in the banned rights."),
        Row(400, "BIRTHDAY_ALREADY", "The target user already has a birthday set."),
        Row(400, "BIRTHDAY_INVALID", "An invalid age was specified, must be between 0 and 150 years."),
        Row(400, "BOOSTS_EMPTY", "No boost slots were specified."),
        Row(400, "BOOSTS_REQUIRED", "The specified channel must first be [boosted by its users](https://core.telegram.org/api/boost) in order to perform this action."),
        Row(400, "BOOST_NOT_MODIFIED", "You're already [boosting](https://core.telegram.org/api/boost) the specified channel."),
        Row(400, "BOOST_PEER_INVALID", "The specified `boost_peer` is invalid."),
        Row(400, "BOTS_TOO_MUCH", "There are too many bots in this chat/channel."),
        Row(400, "BOT_ALREADY_DISABLED", "The connected business bot was already disabled for the specified peer."),
        Row(400, "BOT_APP_BOT_INVALID", "The bot_id passed in the inputBotAppShortName constructor is invalid."),
        Row(400, "BOT_APP_INVALID", "The specified bot app is invalid."),
        Row(400, "BOT_APP_SHORTNAME_INVALID", "The specified bot app short name is invalid."),
        Row(400, "BOT_BUSINESS_MISSING", "The specified bot is not a business bot (the [user](https://core.telegram.org/constructor/user).`bot_business` flag is not set)."),
        Row(400, "BOT_CHANNELS_NA", "Bots can't edit admin privileges."),
        Row(400, "BOT_COMMAND_DESCRIPTION_INVALID", "The specified command description is invalid."),
        Row(400, "BOT_COMMAND_INVALID", "The specified command is invalid."),
        Row(400, "BOT_CREATE_LIMIT_EXCEEDED", "The current user already owns the maximum allowed number of owned bots, as specified by [`bots_create_limit_default` &raquo;](https://core.telegram.org/api/config#bots-create-limit-default) and [`bots_create_limit_premium` &raquo;](https://core.telegram.org/api/config#bots-create-limit-premium); if the current user doesn't have Telegram Premium, upgrading to Premium will allow them to create more bots."),
        Row(400, "BOT_DOMAIN_INVALID", "Bot domain invalid."),
        Row(400, "BOT_FALLBACK_UNSUPPORTED", "The fallback flag can't be set for bots."),
        Row(400, "BOT_GAMES_DISABLED", "Games can't be sent to channels."),
        Row(400, "BOT_GROUPS_BLOCKED", "This bot can't be added to groups."),
        Row(400, "BOT_ID_INVALID", "The specified bot ID is invalid."),
        Row(400, "BOT_INLINE_DISABLED", "This bot can't be used in inline mode."),
        Row(400, "BOT_INVALID", "This is not a valid bot."),
        Row(400, "BOT_INVOICE_INVALID", "The specified invoice is invalid."),
        Row(400, "BOT_METHOD_INVALID", "The specified method cannot be used by bots."),
        Row(400, "BOT_NOT_CONNECTED_YET", "No [business bot](https://core.telegram.org/api/business#connected-bots) is connected to the currently logged in user."),
        Row(400, "BOT_ONESIDE_NOT_AVAIL", "Bots can't pin messages in PM just for themselves."),
        Row(400, "BOT_PAYMENTS_DISABLED", "Please enable bot payments in botfather before calling this method."),
        Row(400, "BOT_RESPONSE_TIMEOUT", "A timeout occurred while fetching data from the bot."),
        Row(400, "BOT_SCORE_NOT_MODIFIED", "The score wasn't modified."),
        Row(400, "BOT_WEBVIEW_DISABLED", "A webview cannot be opened in the specified conditions: emitted for example if `from_bot_menu` or `url` are set and `peer` is not the chat with the bot."),
        Row(400, "BROADCAST_ID_INVALID", "Broadcast ID invalid."),
        Row(400, "BROADCAST_PUBLIC_VOTERS_FORBIDDEN", "You can't forward polls with public voters."),
        Row(400, "BROADCAST_REQUIRED", "This method can only be called on a channel, please use stats.getMegagroupStats for supergroups."),
        Row(400, "BUSINESS_CONNECTION_INVALID", "The `connection_id` passed to the wrapping [invokeWithBusinessConnection](https://core.telegram.org/api/business) call is invalid."),
        Row(400, "BUSINESS_CONNECTION_NOT_ALLOWED", "This method was invoked over a business connection using [invokeWithBusinessConnection](https://core.telegram.org/api/business#connected-bots), but either (1) we're a user, and users cannot invoke methods over a business connection; (2) we're a bot, but business mode was disabled in @botfather or (3); we're a bot, but this method cannot be invoked over a business connection."),
        Row(400, "BUSINESS_PEER_INVALID", "Messages can't be set to the specified peer through the current [business connection](https://core.telegram.org/api/business#connected-bots)."),
        Row(400, "BUSINESS_PEER_USAGE_MISSING", "You cannot send a message to a user through a [business connection](https://core.telegram.org/api/business#connected-bots) if the user hasn't recently contacted us."),
        Row(400, "BUSINESS_RECIPIENTS_EMPTY", "You didn't set any flag in inputBusinessBotRecipients, thus the bot cannot work with *any* peer."),
        Row(400, "BUSINESS_WORK_HOURS_EMPTY", "No work hours were specified."),
        Row(400, "BUSINESS_WORK_HOURS_PERIOD_INVALID", "The specified work hours are invalid, see [here &raquo;](https://core.telegram.org/api/business#opening-hours) for the exact requirements."),
        Row(400, "BUTTON_COPY_TEXT_INVALID", "The specified [keyboardButtonCopy](https://core.telegram.org/constructor/keyboardButtonCopy).`copy_text` is invalid."),
        Row(400, "BUTTON_DATA_INVALID", "The data of one or more of the buttons you provided is invalid."),
        Row(400, "BUTTON_ID_INVALID", "The specified button ID is invalid."),
        Row(400, "BUTTON_INVALID", "The specified button is invalid."),
        Row(400, "BUTTON_POS_INVALID", "The position of one of the keyboard buttons is invalid (i.e. a Game or Pay button not in the first position, and so on...)."),
        Row(400, "BUTTON_TEXT_INVALID", "The specified button text is invalid."),
        Row(400, "BUTTON_TYPE_INVALID", "The type of one or more of the buttons you provided is invalid."),
        Row(400, "BUTTON_URL_INVALID", "Button URL invalid."),
        Row(400, "BUTTON_USER_INVALID", "The `user_id` passed to inputKeyboardButtonUserProfile is invalid!"),
        Row(400, "BUTTON_USER_PRIVACY_RESTRICTED", "The privacy setting of the user specified in a [inputKeyboardButtonUserProfile](https://core.telegram.org/constructor/inputKeyboardButtonUserProfile) button do not allow creating such a button."),
        Row(400, "CALL_ALREADY_ACCEPTED", "The call was already accepted."),
        Row(400, "CALL_ALREADY_DECLINED", "The call was already declined."),
        Row(400, "CALL_NOT_ACTIVE", "The specified call is not active."),
        Row(400, "CALL_OCCUPY_FAILED", "The call failed because the user is already making another call."),
        Row(400, "CALL_PEER_INVALID", "The provided call peer object is invalid."),
        Row(400, "CALL_PROTOCOL_FLAGS_INVALID", "Call protocol flags invalid."),
        Row(400, "CALL_PROTOCOL_LAYER_INVALID", "The specified protocol layer version range is invalid."),
        Row(400, "CDN_METHOD_INVALID", "You can't call this method in a CDN DC."),
        Row(400, "CHANNELS_ADMIN_LOCATED_TOO_MUCH", "The user has reached the limit of public geogroups."),
        Row(400, "CHANNELS_ADMIN_PUBLIC_TOO_MUCH", "You're admin of too many public channels, make some channels private to change the username of this channel."),
        Row(400, "CHANNELS_TOO_MUCH", "You have joined too many channels/supergroups."),
        Row(400, "CHANNEL_FORUM_MISSING", "This supergroup is not a forum."),
        Row(400, "CHANNEL_ID_INVALID", "The specified supergroup ID is invalid."),
        Row(400, "CHANNEL_INVALID", "The provided channel is invalid."),
        Row(400, "CHANNEL_MONOFORUM_UNSUPPORTED", "[Monoforums](https://core.telegram.org/api/channel#monoforums) do not support this feature."),
        Row(400, "CHANNEL_PARICIPANT_MISSING", "The current user is not in the channel."),
        Row(400, "CHANNEL_PRIVATE", "You haven't joined this channel/supergroup."),
        Row(400, "CHANNEL_TOO_BIG", "This channel has too many participants (>1000) to be deleted."),
        Row(400, "CHANNEL_TOO_LARGE", "Channel is too large to be deleted; this error is issued when trying to delete channels with more than 1000 members (subject to change)."),
        Row(400, "CHARGE_ALREADY_REFUNDED", "The transaction was already refunded."),
        Row(400, "CHARGE_ID_EMPTY", "The specified charge_id is empty."),
        Row(400, "CHARGE_ID_INVALID", "The specified charge_id is invalid."),
        Row(400, "CHATLINKS_TOO_MUCH", "Too many [business chat links](https://core.telegram.org/api/business#business-chat-links) were created, please delete some older links."),
        Row(400, "CHATLINK_SLUG_EMPTY", "The specified slug is empty."),
        Row(400, "CHATLINK_SLUG_EXPIRED", "The specified [business chat link](https://core.telegram.org/api/business#business-chat-links) has expired."),
        Row(400, "CHATLISTS_TOO_MUCH", "You have created too many folder links, hitting the `chatlist_invites_limit_default`/`chatlist_invites_limit_premium` [limits &raquo;](https://core.telegram.org/api/config#chatlist-invites-limit-default)."),
        Row(400, "CHATLIST_EXCLUDE_INVALID", "The specified `exclude_peers` are invalid."),
        Row(400, "CHAT_ABOUT_NOT_MODIFIED", "About text has not changed."),
        Row(400, "CHAT_ABOUT_TOO_LONG", "Chat about too long."),
        Row(400, "CHAT_ADMIN_REQUIRED", "You must be an admin in this chat to do this."),
        Row(400, "CHAT_DISCUSSION_UNALLOWED", "You can't enable forum topics in a discussion group linked to a channel."),
        Row(400, "CHAT_FORWARDS_RESTRICTED", "You can't forward messages from a protected chat."),
        Row(400, "CHAT_ID_EMPTY", "The provided chat ID is empty."),
        Row(400, "CHAT_ID_INVALID", "The provided chat id is invalid."),
        Row(400, "CHAT_INVALID", "Invalid chat."),
        Row(400, "CHAT_INVITE_PERMANENT", "You can't set an expiration date on permanent invite links."),
        Row(400, "CHAT_LINK_EXISTS", "The chat is public, you can't hide the history to new users."),
        Row(400, "CHAT_MEMBER_ADD_FAILED", "Could not add participants."),
        Row(400, "CHAT_NOT_MODIFIED", "No changes were made to chat information because the new information you passed is identical to the current information."),
        Row(400, "CHAT_PUBLIC_REQUIRED", "You can only enable join requests in public groups."),
        Row(400, "CHAT_RESTRICTED", "You can't send messages in this chat, you were restricted."),
        Row(400, "CHAT_REVOKE_DATE_UNSUPPORTED", "`min_date` and `max_date` are not available for using with non-user peers."),
        Row(400, "CHAT_SEND_INLINE_FORBIDDEN", "You can't send inline messages in this group."),
        Row(400, "CHAT_TITLE_EMPTY", "No chat title provided."),
        Row(400, "CHAT_TOO_BIG", "This method is not available for groups with more than `chat_read_mark_size_threshold` members, [see client configuration &raquo;](https://core.telegram.org/api/config#client-configuration)."),
        Row(400, "CHAT_WRITE_FORBIDDEN", "You can't write in this chat."),
        Row(400, "CODE_EMPTY", "The provided code is empty."),
        Row(400, "CODE_HASH_INVALID", "Code hash invalid."),
        Row(400, "CODE_INVALID", "Code invalid."),
        Row(400, "COLLECTIBLE_INVALID", "The specified collectible is invalid."),
        Row(400, "COLLECTIBLE_NOT_FOUND", "The specified collectible could not be found."),
        Row(400, "COLLECTION_ID_INVALID", "The specified collection ID is invalid."),
        Row(400, "COLOR_INVALID", "The specified color palette ID was invalid."),
        Row(400, "CONNECTION_API_ID_INVALID", "The provided API id is invalid."),
        Row(400, "CONNECTION_APP_VERSION_EMPTY", "App version is empty."),
        Row(400, "CONNECTION_DEVICE_MODEL_EMPTY", "The specified device model is empty."),
        Row(400, "CONNECTION_ID_INVALID", "The specified connection ID is invalid."),
        Row(400, "CONNECTION_LANG_PACK_INVALID", "The specified language pack is empty."),
        Row(400, "CONNECTION_LAYER_INVALID", "Layer invalid."),
        Row(400, "CONNECTION_NOT_INITED", "Please initialize the connection using initConnection before making queries."),
        Row(400, "CONNECTION_SYSTEM_EMPTY", "The specified system version is empty."),
        Row(400, "CONNECTION_SYSTEM_LANG_CODE_EMPTY", "The specified system language code is empty."),
        Row(400, "CONTACT_ADD_MISSING", "Contact to add is missing."),
        Row(400, "CONTACT_ID_INVALID", "The provided contact ID is invalid."),
        Row(400, "CONTACT_MISSING", "The specified user is not a contact."),
        Row(400, "CONTACT_NAME_EMPTY", "Contact name empty."),
        Row(400, "CONTACT_REQ_MISSING", "Missing contact request."),
        Row(400, "CREATE_CALL_FAILED", "An error occurred while creating the call."),
        Row(400, "CREDENTIAL_INVALID", "The specified credential is invalid."),
        Row(400, "CURRENCY_TOTAL_AMOUNT_INVALID", "The total amount of all prices is invalid."),
        Row(400, "CUSTOM_REACTIONS_TOO_MANY", "Too many custom reactions were specified."),
        Row(400, "DATA_HASH_SIZE_INVALID", "The size of the specified secureValueErrorData.data_hash is invalid."),
        Row(400, "DATA_INVALID", "Encrypted data invalid."),
        Row(400, "DATA_JSON_INVALID", "The provided JSON data is invalid."),
        Row(400, "DATA_TOO_LONG", "Data too long."),
        Row(400, "DATE_EMPTY", "Date empty."),
        Row(400, "DC_ID_INVALID", "The provided DC ID is invalid."),
        Row(400, "DH_G_A_INVALID", "g_a invalid."),
        Row(400, "DOCUMENT_INVALID", "The specified document is invalid."),
        Row(400, "EFFECT_CHAT_INVALID", "Message [effects](https://core.telegram.org/api/effects) can only be used in private 1-on-1 chats, but the caller tried to send a message with an effect to a group or channel."),
        Row(400, "EFFECT_ID_INVALID", "The specified effect ID is invalid."),
        Row(400, "EMAIL_HASH_EXPIRED", "Email hash expired."),
        Row(400, "EMAIL_INSTALL_MISSING", "Attempting to send a code to the recovery email, but no email is configured."),
        Row(400, "EMAIL_INVALID", "The specified email is invalid."),
        Row(400, "EMAIL_NOT_ALLOWED", "The specified email cannot be used to complete the operation."),
        Row(400, "EMAIL_NOT_SETUP", "In order to change the login email with emailVerifyPurposeLoginChange, an existing login email must already be set using emailVerifyPurposeLoginSetup."),
        Row(400, "EMAIL_UNCONFIRMED", "Email unconfirmed."),
        Row(400, "EMAIL_UNCONFIRMED_%d", "The provided email isn't confirmed, %d is the length of the verification code that was just sent to the email: use [account.verifyEmail](https://core.telegram.org/method/account.verifyEmail) to enter the received verification code and enable the recovery email."),
        Row(400, "EMAIL_VERIFY_EXPIRED", "The verification email has expired."),
        Row(400, "EMOJI_INVALID", "The specified theme emoji is valid."),
        Row(400, "EMOJI_MARKUP_INVALID", "The specified `video_emoji_markup` was invalid."),
        Row(400, "EMOJI_NOT_MODIFIED", "The theme wasn't changed."),
        Row(400, "EMOTICON_EMPTY", "The emoji is empty."),
        Row(400, "EMOTICON_INVALID", "The specified emoji is invalid."),
        Row(400, "EMOTICON_STICKERPACK_MISSING", "inputStickerSetDice.emoji cannot be empty."),
        Row(400, "ENCRYPTED_MESSAGE_INVALID", "Encrypted message invalid."),
        Row(400, "ENCRYPTION_ALREADY_ACCEPTED", "Secret chat already accepted."),
        Row(400, "ENCRYPTION_ALREADY_DECLINED", "The secret chat was already declined."),
        Row(400, "ENCRYPTION_DECLINED", "The secret chat was declined."),
        Row(400, "ENCRYPTION_ID_INVALID", "The provided secret chat ID is invalid."),
        Row(400, "ENTITIES_TOO_LONG", "You provided too many styled message entities."),
        Row(400, "ENTITY_BOUNDS_INVALID", "A specified [entity offset or length](https://core.telegram.org/api/entities#entity-length) is invalid, see [here &raquo;](https://core.telegram.org/api/entities#entity-length) for info on how to properly compute the entity offset/length."),
        Row(400, "ENTITY_DATE_FORMAT_INVALID", "One of the passed messageEntityFormattedDate objects has an invalid format (i.e. an invalid combination of the format flags)."),
        Row(400, "ENTITY_DATE_INVALID", "One of the passed messageEntityFormattedDate objects has an invalid date: the allowed value ranges from `0` to the current date plus 1098 days (`time()+1098*86400`)."),
        Row(400, "ENTITY_DATE_TOO_LONG", "The maximum text span that can be covered by a date entity is 31 UTF-16 code units if any of the date formatting flags is set, or 127 UTF-16 code units without.  ."),
        Row(400, "ENTITY_MENTION_USER_INVALID", "You mentioned an invalid user."),
        Row(400, "ERROR_TEXT_EMPTY", "The provided error message is empty."),
        Row(400, "EXPIRES_AT_INVALID", "The specified `expires_at` timestamp is invalid."),
        Row(400, "EXPIRE_DATE_INVALID", "The specified expiration date is invalid."),
        Row(400, "EXPORT_CARD_INVALID", "Provided card is invalid."),
        Row(400, "EXTENDED_MEDIA_AMOUNT_INVALID", "The specified `stars_amount` of the passed [inputMediaPaidMedia](https://core.telegram.org/constructor/inputMediaPaidMedia) is invalid."),
        Row(400, "EXTENDED_MEDIA_EMPTY", "The specified extended media is empty."),
        Row(400, "EXTENDED_MEDIA_INVALID", "The specified paid media is invalid."),
        Row(400, "EXTENDED_MEDIA_PEER_INVALID", "Paid media is not allowed for the target peer."),
        Row(400, "EXTERNAL_URL_INVALID", "External URL invalid."),
        Row(400, "FILE_CONTENT_TYPE_INVALID", "File content-type is invalid."),
        Row(400, "FILE_EMTPY", "An empty file was provided."),
        Row(400, "FILE_ID_INVALID", "The provided file id is invalid."),
        Row(400, "FILE_MIGRATE_%d", "The file currently being accessed is stored in DC %d, please re-send the query to that DC."),
        Row(400, "FILE_PARTS_INVALID", "The number of file parts is invalid."),
        Row(400, "FILE_PART_%d_MISSING", "Part %d of the file is missing from storage. Try repeating the method call to resave the part."),
        Row(400, "FILE_PART_EMPTY", "The provided file part is empty."),
        Row(400, "FILE_PART_INVALID", "The file part number is invalid."),
        Row(400, "FILE_PART_LENGTH_INVALID", "The length of a file part is invalid."),
        Row(400, "FILE_PART_SIZE_CHANGED", "Provided file part size has changed."),
        Row(400, "FILE_PART_SIZE_INVALID", "The provided file part size is invalid."),
        Row(400, "FILE_PART_TOO_BIG", "The uploaded file part is too big."),
        Row(400, "FILE_PART_TOO_SMALL", "The size of the uploaded file part is too small, please see the documentation for the allowed sizes."),
        Row(400, "FILE_REFERENCE_%d_EMPTY", "The file reference of the media file at offset %d in the multi_media array is invalid."),
        Row(400, "FILE_REFERENCE_%d_EXPIRED", "The file reference of the media file at index %d in the passed media array expired, it [must be refreshed as specified in the documentation](https://core.telegram.org/api/file-references). ."),
        Row(400, "FILE_REFERENCE_%d_INVALID", "The [file reference](https://core.telegram.org/api/file-references) of the media file at index %d in the passed media array is invalid."),
        Row(400, "FILE_REFERENCE_EMPTY", "An empty [file reference](https://core.telegram.org/api/file-references) was specified."),
        Row(400, "FILE_REFERENCE_EXPIRED", "File reference expired, it must be refetched as described in [the documentation](https://core.telegram.org/api/file-references)."),
        Row(400, "FILE_REFERENCE_INVALID", "The specified [file reference](https://core.telegram.org/api/file-references) is invalid."),
        Row(400, "FILE_TITLE_EMPTY", "An empty file title was specified."),
        Row(400, "FILE_TOKEN_INVALID", "The master DC did not accept the `file_token` (e.g., the token has expired). Continue downloading the file from the master DC using upload.getFile."),
        Row(400, "FILTER_ID_INVALID", "The specified filter ID is invalid."),
        Row(400, "FILTER_INCLUDE_EMPTY", "The include_peers vector of the filter is empty."),
        Row(400, "FILTER_NOT_SUPPORTED", "The specified filter cannot be used in this context."),
        Row(400, "FILTER_TITLE_EMPTY", "The title field of the filter is empty."),
        Row(400, "FIRSTNAME_INVALID", "The first name is invalid."),
        Row(400, "FOLDER_ID_EMPTY", "An empty folder ID was specified."),
        Row(400, "FOLDER_ID_INVALID", "Invalid folder ID."),
        Row(400, "FORM_EXPIRED", "The form was generated more than 10 minutes ago and has expired, please re-generate it using [payments.getPaymentForm](https://core.telegram.org/method/payments.getPaymentForm) and pass the new `form_id`."),
        Row(400, "FORM_ID_EMPTY", "The specified form ID is empty."),
        Row(400, "FORM_SUBMIT_DUPLICATE", "The same payment form was already submitted.  ."),
        Row(400, "FORM_UNSUPPORTED", "Please update your client."),
        Row(400, "FORUM_ENABLED", "You can't execute the specified action because the group is a [forum](https://core.telegram.org/api/forum), disable forum functionality to continue."),
        Row(400, "FRESH_CHANGE_ADMINS_FORBIDDEN", "You were just elected admin, you can't add or modify other admins yet."),
        Row(400, "FROM_MESSAGE_BOT_DISABLED", "Bots can't use fromMessage min constructors."),
        Row(400, "FROM_PEER_INVALID", "The specified from_id is invalid."),
        Row(400, "FROZEN_PARTICIPANT_MISSING", "The current account is [frozen](https://core.telegram.org/api/auth#frozen-accounts), and cannot access the specified peer."),
        Row(400, "GAME_BOT_INVALID", "Bots can't send another bot's game."),
        Row(400, "GENERAL_MODIFY_ICON_FORBIDDEN", "You can't modify the icon of the \"General\" topic."),
        Row(400, "GEO_POINT_INVALID", "Invalid geoposition provided."),
        Row(400, "GIFT_MONTHS_INVALID", "The value passed in invoice.inputInvoicePremiumGiftStars.months is invalid."),
        Row(400, "GIFT_SLUG_EXPIRED", "The specified gift slug has expired."),
        Row(400, "GIFT_SLUG_INVALID", "The specified slug is invalid."),
        Row(400, "GIFT_STARS_INVALID", "The specified amount of stars is invalid."),
        Row(400, "GIF_CONTENT_TYPE_INVALID", "GIF content-type invalid."),
        Row(400, "GIF_ID_INVALID", "The provided GIF ID is invalid."),
        Row(400, "GRAPH_EXPIRED_RELOAD", "This graph has expired, please obtain a new graph token."),
        Row(400, "GRAPH_INVALID_RELOAD", "Invalid graph token provided, please reload the stats and provide the updated token."),
        Row(400, "GRAPH_OUTDATED_RELOAD", "The graph is outdated, please get a new async token using stats.getBroadcastStats."),
        Row(400, "GROUPCALL_ALREADY_DISCARDED", "The group call was already discarded."),
        Row(400, "GROUPCALL_FORBIDDEN", "The specified group call cannot be used in this context."),
        Row(400, "GROUPCALL_INVALID", "The specified group call is invalid."),
        Row(400, "GROUPCALL_JOIN_MISSING", "You haven't joined this group call."),
        Row(400, "GROUPCALL_NOT_MODIFIED", "Group call settings weren't modified."),
        Row(400, "GROUPCALL_SSRC_DUPLICATE_MUCH", "The app needs to retry joining the group call with a new SSRC value."),
        Row(400, "GROUPED_MEDIA_INVALID", "Invalid grouped media."),
        Row(400, "HASHTAG_INVALID", "The specified hashtag is invalid."),
        Row(400, "HASH_INVALID", "The provided hash is invalid."),
        Row(400, "HASH_SIZE_INVALID", "The size of the specified secureValueError.hash is invalid."),
        Row(400, "HIDE_REQUESTER_MISSING", "The join request was missing or was already handled."),
        Row(400, "ID_EXPIRED", "The passed prepared inline message ID has expired."),
        Row(400, "ID_INVALID", "The passed ID is invalid."),
        Row(400, "IMAGE_PROCESS_FAILED", "Failure while processing image."),
        Row(400, "IMPORT_FILE_INVALID", "The specified chat export file is invalid."),
        Row(400, "IMPORT_FORMAT_DATE_INVALID", "The date specified in the import file is invalid."),
        Row(400, "IMPORT_FORMAT_UNRECOGNIZED", "The specified chat export file was exported from an unsupported chat app."),
        Row(400, "IMPORT_ID_INVALID", "The specified import ID is invalid."),
        Row(400, "IMPORT_TOKEN_INVALID", "The specified token is invalid."),
        Row(400, "INLINE_RESULT_EXPIRED", "The inline query expired."),
        Row(400, "INPUT_CHATLIST_INVALID", "The specified folder is invalid."),
        Row(400, "INPUT_CONSTRUCTOR_INVALID", "The specified TL constructor is invalid."),
        Row(400, "INPUT_FETCH_ERROR", "An error occurred while parsing the provided TL constructor."),
        Row(400, "INPUT_FETCH_FAIL", "An error occurred while parsing the provided TL constructor."),
        Row(400, "INPUT_FILE_INVALID", "The specified [InputFile](https://core.telegram.org/type/InputFile) is invalid."),
        Row(400, "INPUT_FILTER_INVALID", "The specified filter is invalid."),
        Row(400, "INPUT_LAYER_INVALID", "The specified layer is invalid."),
        Row(400, "INPUT_METHOD_INVALID", "The specified method is invalid."),
        Row(400, "INPUT_PEERS_EMPTY", "The specified peer array is empty."),
        Row(400, "INPUT_PURPOSE_INVALID", "The specified payment purpose is invalid."),
        Row(400, "INPUT_REQUEST_TOO_LONG", "The request payload is too long."),
        Row(400, "INPUT_STARS_AMOUNT_INVALID", "The specified offer amount in stars is invalid, see [here &raquo;](https://core.telegram.org/api/gifts#collectible-gift-purchase-offers) for the allowed range."),
        Row(400, "INPUT_STARS_NANOS_INVALID", " The specified offer amount in nanotons is invalid, see [here &raquo;](https://core.telegram.org/api/gifts#collectible-gift-purchase-offers) for the allowed range."),
        Row(400, "INPUT_TEXT_EMPTY", "The specified text is empty."),
        Row(400, "INPUT_TEXT_TOO_LONG", "The specified text is too long."),
        Row(400, "INPUT_USER_DEACTIVATED", "The specified user was deleted."),
        Row(400, "INVITES_TOO_MUCH", "The maximum number of per-folder invites specified by the `chatlist_invites_limit_default`/`chatlist_invites_limit_premium` [client configuration parameters &raquo;](https://core.telegram.org/api/config#chatlist-invites-limit-default) was reached."),
        Row(400, "INVITE_FORBIDDEN_WITH_JOINAS", "If the user has anonymously joined a group call as a channel, they can't invite other users to the group call because that would cause deanonymization, because the invite would be sent using the original user ID, not the anonymized channel ID."),
        Row(400, "INVITE_HASH_EMPTY", "The invite hash is empty."),
        Row(400, "INVITE_HASH_EXPIRED", "The invite link has expired."),
        Row(400, "INVITE_HASH_INVALID", "The invite hash is invalid."),
        Row(400, "INVITE_REQUEST_SENT", "You have successfully requested to join this chat or channel."),
        Row(400, "INVITE_REVOKED_MISSING", "The specified invite link was already revoked or is invalid."),
        Row(400, "INVITE_SLUG_EMPTY", "The specified invite slug is empty."),
        Row(400, "INVITE_SLUG_EXPIRED", "The specified chat folder link has expired."),
        Row(400, "INVITE_SLUG_INVALID", "The specified invitation slug is invalid."),
        Row(400, "INVOICE_INVALID", "The specified invoice is invalid."),
        Row(400, "INVOICE_PAYLOAD_INVALID", "The specified invoice payload is invalid."),
        Row(400, "JOIN_AS_PEER_INVALID", "The specified peer cannot be used to join a group call."),
        Row(400, "LANGUAGE_INVALID", "The specified lang_code is invalid."),
        Row(400, "LANG_CODE_INVALID", "The specified language code is invalid."),
        Row(400, "LANG_CODE_NOT_SUPPORTED", "The specified language code is not supported."),
        Row(400, "LANG_PACK_INVALID", "The provided language pack is invalid."),
        Row(400, "LASTNAME_INVALID", "The last name is invalid."),
        Row(400, "LIMIT_INVALID", "The provided limit is invalid."),
        Row(400, "LIMIT_PER_POST_INVALID", "The specified reactions_limit value is invalid."),
        Row(400, "LINK_NOT_MODIFIED", "Discussion link not modified."),
        Row(400, "LOCATION_INVALID", "The provided location is invalid."),
        Row(400, "MANAGER_INVALID", "The specified manager bot is invalid."),
        Row(400, "MANAGER_PERMISSION_MISSING", "The specified manager bot does not have the [user](https://core.telegram.org/constructor/user).`bot_can_manage_bots` flag set."),
        Row(400, "MAX_DATE_INVALID", "The specified maximum date is invalid."),
        Row(400, "MAX_ID_INVALID", "The provided max ID is invalid."),
        Row(400, "MAX_QTS_INVALID", "The specified max_qts is invalid."),
        Row(400, "MD5_CHECKSUM_INVALID", "The MD5 checksums do not match."),
        Row(400, "MEDIA_ALREADY_PAID", "You already paid for the specified media."),
        Row(400, "MEDIA_CAPTION_TOO_LONG", "The caption is too long."),
        Row(400, "MEDIA_EMPTY", "The provided media object is invalid."),
        Row(400, "MEDIA_FILE_INVALID", "The specified media file is invalid."),
        Row(400, "MEDIA_GROUPED_INVALID", "You tried to send media of different types in an album."),
        Row(400, "MEDIA_INVALID", "Media invalid."),
        Row(400, "MEDIA_NEW_INVALID", "The new media is invalid."),
        Row(400, "MEDIA_PREV_INVALID", "Previous media invalid."),
        Row(400, "MEDIA_TTL_INVALID", "The specified media TTL is invalid."),
        Row(400, "MEDIA_TYPE_INVALID", "The specified media type cannot be used in stories."),
        Row(400, "MEDIA_VIDEO_STORY_MISSING", "A non-story video cannot be repubblished as a story (emitted when trying to resend a non-story video as a story using inputDocument)."),
        Row(400, "MEGAGROUP_GEO_REQUIRED", "This method can only be invoked on a geogroup."),
        Row(400, "MEGAGROUP_ID_INVALID", "Invalid supergroup ID."),
        Row(400, "MEGAGROUP_PREHISTORY_HIDDEN", "Group with hidden history for new members can't be set as discussion groups."),
        Row(400, "MEGAGROUP_REQUIRED", "You can only use this method on a supergroup."),
        Row(400, "MESSAGE_EDIT_TIME_EXPIRED", "You can't edit this message anymore, too much time has passed since its creation."),
        Row(400, "MESSAGE_EMPTY", "The provided message is empty."),
        Row(400, "MESSAGE_IDS_EMPTY", "No message ids were provided."),
        Row(400, "MESSAGE_ID_INVALID", "The provided message id is invalid."),
        Row(400, "MESSAGE_NOT_MODIFIED", "The provided message data is identical to the previous message data, the message wasn't modified."),
        Row(400, "MESSAGE_NOT_READ_YET", "The specified message wasn't read yet."),
        Row(400, "MESSAGE_POLL_CLOSED", "Poll closed."),
        Row(400, "MESSAGE_REQUIRED", "A non-empty list of IDs must be passed to `id`."),
        Row(400, "MESSAGE_TOO_LONG", "The provided message is too long."),
        Row(400, "MESSAGE_TOO_OLD", "The message is too old, the requested information is not available."),
        Row(400, "METHOD_INVALID", "The specified method is invalid."),
        Row(400, "MIN_DATE_INVALID", "The specified minimum date is invalid."),
        Row(400, "MONTH_INVALID", "The number of months specified in inputInvoicePremiumGiftStars.months is invalid."),
        Row(400, "MSG_ID_INVALID", "Invalid message ID provided."),
        Row(400, "MSG_TOO_OLD", "[`chat_read_mark_expire_period` seconds](https://core.telegram.org/api/config#chat-read-mark-expire-period) have passed since the message was sent, read receipts were deleted."),
        Row(400, "MSG_VOICE_MISSING", "The specified message is not a voice message."),
        Row(400, "MSG_VOICE_TOO_LONG", "The specified voice message is too long to be transcribed."),
        Row(400, "MSG_WAIT_FAILED", "A waiting call returned an error."),
        Row(400, "MULTI_MEDIA_TOO_LONG", "Too many media files for album."),
        Row(400, "NAME_INVALID", "The specified bot name is invalid."),
        Row(400, "NEED_ACTION_MISSING", "The caller didn't specify a valid action (either save or suggest) for the contact profile photo upload."),
        Row(400, "NEW_SALT_INVALID", "The new salt is invalid."),
        Row(400, "NEW_SETTINGS_EMPTY", "No password is set on the current account, and no new password was specified in `new_settings`."),
        Row(400, "NEW_SETTINGS_INVALID", "The new password settings are invalid."),
        Row(400, "NEXT_OFFSET_INVALID", "The specified offset is longer than 64 bytes."),
        Row(400, "NOGENERAL_HIDE_FORBIDDEN", "Only the \"General\" topic with `id=1` can be hidden."),
        Row(400, "NOT_ELIGIBLE", "The current user is not eligible to join the Peer-to-Peer Login Program."),
        Row(400, "NOT_JOINED", "The current user hasn't joined the Peer-to-Peer Login Program."),
        Row(400, "NO_PAYMENT_NEEDED", "The upgrade/transfer of the specified gift was already paid for or is free."),
        Row(400, "OFFSET_INVALID", "The provided offset is invalid."),
        Row(400, "OFFSET_PEER_ID_INVALID", "The provided offset peer is invalid."),
        Row(400, "OPTIONS_TOO_MUCH", "Too many options provided."),
        Row(400, "OPTION_INVALID", "Invalid option selected."),
        Row(400, "ORDER_INVALID", "The specified username order is invalid."),
        Row(400, "PACK_SHORT_NAME_INVALID", "Short pack name invalid."),
        Row(400, "PACK_SHORT_NAME_OCCUPIED", "A stickerpack with this name already exists."),
        Row(400, "PACK_TITLE_INVALID", "The stickerpack title is invalid."),
        Row(400, "PACK_TYPE_INVALID", "The masks and emojis flags are mutually exclusive."),
        Row(400, "PARENT_PEER_INVALID", "The specified `parent_peer` is invalid."),
        Row(400, "PARTICIPANTS_TOO_FEW", "Not enough participants."),
        Row(400, "PARTICIPANT_ID_INVALID", "The specified participant ID is invalid."),
        Row(400, "PARTICIPANT_JOIN_MISSING", "Trying to enable a presentation, when the user hasn't joined the Video Chat with [phone.joinGroupCall](https://core.telegram.org/method/phone.joinGroupCall)."),
        Row(400, "PARTICIPANT_VERSION_OUTDATED", "The other participant does not use an up to date telegram client with support for calls."),
        Row(400, "PASSKEY_ORIGIN_MISMATCH", "Third-party clients currently don't support passkeys even when changing the origin."),
        Row(400, "PASSWORD_EMPTY", "The provided password is empty."),
        Row(400, "PASSWORD_HASH_INVALID", "The provided password hash is invalid."),
        Row(400, "PASSWORD_MISSING", "You must [enable 2FA](https://core.telegram.org/api/srp) before executing this operation."),
        Row(400, "PASSWORD_RECOVERY_EXPIRED", "The recovery code has expired."),
        Row(400, "PASSWORD_RECOVERY_NA", "No email was set, can't recover password via email."),
        Row(400, "PASSWORD_REQUIRED", "A [2FA password](https://core.telegram.org/api/srp) must be configured to use Telegram Passport."),
        Row(400, "PASSWORD_TOO_FRESH_%d", "The password was modified less than 24 hours ago, try again in %d seconds."),
        Row(400, "PAYMENT_CREDENTIALS_INVALID", "The specified payment credentials are invalid."),
        Row(400, "PAYMENT_PROVIDER_INVALID", "The specified payment provider is invalid."),
        Row(400, "PAYMENT_REQUIRED", "Payment is required for this action, see [here &raquo;](https://core.telegram.org/api/gifts) for more info."),
        Row(400, "PEERS_LIST_EMPTY", "The specified list of peers is empty."),
        Row(400, "PEER_FLOOD", "The current account is spamreported, you cannot execute this action, check @spambot for more info."),
        Row(400, "PEER_HISTORY_EMPTY", "You can't pin an empty chat with a user."),
        Row(400, "PEER_ID_INVALID", "The provided peer id is invalid."),
        Row(400, "PEER_ID_NOT_SUPPORTED", "The provided peer ID is not supported."),
        Row(400, "PEER_TYPES_INVALID", "The passed [keyboardButtonSwitchInline](https://core.telegram.org/constructor/keyboardButtonSwitchInline).`peer_types` field is invalid."),
        Row(400, "PERSISTENT_TIMESTAMP_EMPTY", "Persistent timestamp empty."),
        Row(400, "PERSISTENT_TIMESTAMP_INVALID", "Persistent timestamp invalid."),
        Row(400, "PHONE_CODE_EMPTY", "phone_code is missing."),
        Row(400, "PHONE_CODE_EXPIRED", "The phone code you provided has expired."),
        Row(400, "PHONE_CODE_HASH_EMPTY", "phone_code_hash is missing."),
        Row(400, "PHONE_CODE_INVALID", "The provided phone code is invalid."),
        Row(400, "PHONE_HASH_EXPIRED", "An invalid or expired `phone_code_hash` was provided."),
        Row(400, "PHONE_NOT_OCCUPIED", "No user is associated to the specified phone number."),
        Row(400, "PHONE_NUMBER_APP_SIGNUP_FORBIDDEN", "You can't sign up using this app."),
        Row(400, "PHONE_NUMBER_BANNED", "The provided phone number is banned from telegram."),
        Row(400, "PHONE_NUMBER_FLOOD", "You asked for the code too many times."),
        Row(400, "PHONE_NUMBER_INVALID", "The phone number is invalid."),
        Row(400, "PHONE_NUMBER_OCCUPIED", "The phone number is already in use."),
        Row(400, "PHONE_NUMBER_UNOCCUPIED", "The phone number is not yet being used."),
        Row(400, "PHONE_PASSWORD_PROTECTED", "This phone is password protected."),
        Row(400, "PHOTO_CONTENT_TYPE_INVALID", "Photo mime-type invalid."),
        Row(400, "PHOTO_CONTENT_URL_EMPTY", "Photo URL invalid."),
        Row(400, "PHOTO_CROP_FILE_MISSING", "Photo crop file missing."),
        Row(400, "PHOTO_CROP_SIZE_SMALL", "Photo is too small."),
        Row(400, "PHOTO_EXT_INVALID", "The extension of the photo is invalid."),
        Row(400, "PHOTO_FILE_MISSING", "Profile photo file missing."),
        Row(400, "PHOTO_ID_INVALID", "Photo ID invalid."),
        Row(400, "PHOTO_INVALID", "Photo invalid."),
        Row(400, "PHOTO_INVALID_DIMENSIONS", "The photo dimensions are invalid."),
        Row(400, "PHOTO_SAVE_FILE_INVALID", "Internal issues, try again later."),
        Row(400, "PHOTO_THUMB_URL_EMPTY", "Photo thumbnail URL is empty."),
        Row(400, "PINNED_DIALOGS_TOO_MUCH", "Too many pinned dialogs."),
        Row(400, "PINNED_TOO_MUCH", "There are too many pinned topics, unpin some first."),
        Row(400, "PINNED_TOPIC_NOT_MODIFIED", "The specified topic is already pinned."),
        Row(400, "PIN_RESTRICTED", "You can't pin messages."),
        Row(400, "POLL_ANSWERS_INVALID", "Invalid poll answers were provided."),
        Row(400, "POLL_ANSWER_INVALID", "One of the poll answers is not acceptable."),
        Row(400, "POLL_OPTION_DUPLICATE", "Duplicate poll options provided."),
        Row(400, "POLL_OPTION_INVALID", "Invalid poll option provided."),
        Row(400, "POLL_QUESTION_INVALID", "One of the poll questions is not acceptable."),
        Row(400, "PREMIUM_ACCOUNT_REQUIRED", "A premium account is required to execute this action."),
        Row(400, "PREMIUM_PURPOSE_INVALID", "The specified InputStorePaymentPurpose is invalid."),
        Row(400, "PRICING_CHAT_INVALID", "The pricing for the [subscription](https://core.telegram.org/api/subscriptions) is invalid, the maximum price is specified in the [`stars_subscription_amount_max` config key &raquo;](https://core.telegram.org/api/config#stars-subscription-amount-max)."),
        Row(400, "PRIVACY_KEY_INVALID", "The privacy key is invalid."),
        Row(400, "PRIVACY_TOO_LONG", "Too many privacy rules were specified, the current limit is 1000."),
        Row(400, "PRIVACY_VALUE_INVALID", "The specified privacy rule combination is invalid."),
        Row(400, "PUBLIC_BROADCAST_EXPECTED", "`channel` only accepts a channel, but a supergroup was passed."),
        Row(400, "PUBLIC_KEY_INVALID", "The specified e2e public key is invalid."),
        Row(400, "PUBLIC_KEY_REQUIRED", "A public key is required."),
        Row(400, "PURPOSE_INVALID", "The specified payment purpose is invalid."),
        Row(400, "QUERY_ID_EMPTY", "The query ID is empty."),
        Row(400, "QUERY_ID_INVALID", "The query ID is invalid."),
        Row(400, "QUERY_TOO_SHORT", "The query string is too short."),
        Row(400, "QUICK_REPLIES_BOT_NOT_ALLOWED", "[Quick replies](https://core.telegram.org/api/business#quick-reply-shortcuts) cannot be used by bots."),
        Row(400, "QUICK_REPLIES_TOO_MUCH", "A maximum of [appConfig.`quick_replies_limit`](https://core.telegram.org/api/config#quick-replies-limit) shortcuts may be created, the limit was reached."),
        Row(400, "QUIZ_ANSWER_MISSING", "You can forward a quiz while hiding the original author only after choosing an option in the quiz."),
        Row(400, "QUIZ_CORRECT_ANSWERS_EMPTY", "No correct quiz answer was specified."),
        Row(400, "QUIZ_CORRECT_ANSWERS_TOO_MUCH", "You specified too many correct answers in a quiz, quizzes can only have one right answer!"),
        Row(400, "QUIZ_CORRECT_ANSWER_INVALID", "An invalid value was provided to the correct_answers field."),
        Row(400, "QUIZ_MULTIPLE_INVALID", "Quizzes can't have the multiple_choice flag set!"),
        Row(400, "QUOTE_TEXT_INVALID", "The specified `reply_to`.`quote_text` field is invalid."),
        Row(400, "RAISE_HAND_FORBIDDEN", "You cannot raise your hand."),
        Row(400, "RANDOM_ID_DUPLICATE", "You provided a random ID that was already used."),
        Row(400, "RANDOM_ID_EMPTY", "Random ID empty."),
        Row(400, "RANDOM_ID_EXPIRED", "The specified `random_id` was expired (most likely it didn't follow the required `uint64_t random_id = (time() << 32) | ((uint64_t)random_uint32_t())` format, or the specified time is too far in the past)."),
        Row(400, "RANDOM_ID_INVALID", "A provided random ID is invalid."),
        Row(400, "RANDOM_LENGTH_INVALID", "Random length invalid."),
        Row(400, "RANGES_INVALID", "Invalid range provided."),
        Row(400, "REACTIONS_COUNT_INVALID", "The specified number of reactions is invalid."),
        Row(400, "REACTIONS_TOO_MANY", "The message already has exactly `reactions_uniq_max` reaction emojis, you can't react with a new emoji, see [the docs for more info &raquo;](https://core.telegram.org/api/config#client-configuration)."),
        Row(400, "REACTION_EMPTY", "Empty reaction provided."),
        Row(400, "REACTION_INVALID", "The specified reaction is invalid."),
        Row(400, "RECEIPT_EMPTY", "The specified receipt is empty."),
        Row(400, "REPLY_MARKUP_BUY_EMPTY", "Reply markup for buy button empty."),
        Row(400, "REPLY_MARKUP_GAME_EMPTY", "A game message is being edited, but the newly provided keyboard doesn't have a keyboardButtonGame button."),
        Row(400, "REPLY_MARKUP_INVALID", "The provided reply markup is invalid."),
        Row(400, "REPLY_MARKUP_TOO_LONG", "The specified reply_markup is too long."),
        Row(400, "REPLY_MESSAGES_TOO_MUCH", "Each shortcut can contain a maximum of [appConfig.`quick_reply_messages_limit`](https://core.telegram.org/api/config#quick-reply-messages-limit) messages, the limit was reached."),
        Row(400, "REPLY_MESSAGE_ID_INVALID", "The specified reply-to message ID is invalid."),
        Row(400, "REPLY_TO_INVALID", "The specified `reply_to` field is invalid."),
        Row(400, "REPLY_TO_MONOFORUM_PEER_INVALID", "The specified inputReplyToMonoForum.monoforum_peer_id is invalid."),
        Row(400, "REPLY_TO_USER_INVALID", "The replied-to user is invalid."),
        Row(400, "REQUEST_MSG_EXPIRED", "The request specified in request_msg_id has already expired."),
        Row(400, "REQUEST_TOKEN_INVALID", "The master DC did not accept the `request_token` from the CDN DC. Continue downloading the file from the master DC using upload.getFile."),
        Row(400, "RESELL_STARS_TOO_FEW", "The offered price is too low."),
        Row(400, "RESELL_STARS_TOO_MUCH", "The offered price is too high."),
        Row(400, "RESET_REQUEST_MISSING", "No password reset is in progress."),
        Row(400, "RESULTS_TOO_MUCH", "Too many results were provided."),
        Row(400, "RESULT_ID_DUPLICATE", "You provided a duplicate result ID."),
        Row(400, "RESULT_ID_EMPTY", "Result ID empty."),
        Row(400, "RESULT_ID_INVALID", "One of the specified result IDs is invalid."),
        Row(400, "RESULT_TYPE_INVALID", "Result type invalid."),
        Row(400, "REVOTE_NOT_ALLOWED", "You cannot change your vote."),
        Row(400, "RIGHTS_NOT_MODIFIED", "The new admin rights are equal to the old rights, no change was made."),
        Row(400, "RINGTONE_INVALID", "The specified ringtone is invalid."),
        Row(400, "RINGTONE_MIME_INVALID", "The MIME type for the ringtone is invalid."),
        Row(400, "RSA_DECRYPT_FAILED", "Internal RSA decryption failed."),
        Row(400, "SAVED_ID_EMPTY", "The passed inputSavedStarGiftChat.saved_id is empty."),
        Row(400, "SCHEDULE_BOT_NOT_ALLOWED", "Bots cannot schedule messages."),
        Row(400, "SCHEDULE_DATE_INVALID", "Invalid schedule date provided."),
        Row(400, "SCHEDULE_DATE_TOO_LATE", "You can't schedule a message this far in the future."),
        Row(400, "SCHEDULE_STATUS_PRIVATE", "Can't schedule until user is online, if the user's last seen timestamp is hidden by their privacy settings."),
        Row(400, "SCHEDULE_TOO_MUCH", "There are too many scheduled messages."),
        Row(400, "SCORE_INVALID", "The specified game score is invalid."),
        Row(400, "SEARCH_QUERY_EMPTY", "The search query is empty."),
        Row(400, "SEARCH_WITH_LINK_NOT_SUPPORTED", "You cannot provide a search query and an invite link at the same time."),
        Row(400, "SECONDS_INVALID", "Invalid duration provided."),
        Row(400, "SECURE_SECRET_REQUIRED", "A secure secret is required."),
        Row(400, "SELF_DELETE_RESTRICTED", "Business bots can't delete messages just for the user, `revoke` **must** be set."),
        Row(400, "SEND_AS_PEER_INVALID", "You can't send messages as the specified peer."),
        Row(400, "SEND_MESSAGE_GAME_INVALID", "An inputBotInlineMessageGame can only be contained in an inputBotInlineResultGame, not in an inputBotInlineResult/inputBotInlineResultPhoto/etc."),
        Row(400, "SEND_MESSAGE_MEDIA_INVALID", "Invalid media provided."),
        Row(400, "SEND_MESSAGE_TYPE_INVALID", "The message type is invalid."),
        Row(400, "SESSION_TOO_FRESH_%d", "This session was created less than 24 hours ago, try again in %d seconds."),
        Row(400, "SETTINGS_INVALID", "Invalid settings were provided."),
        Row(400, "SHA256_HASH_INVALID", "The provided SHA256 hash is invalid."),
        Row(400, "SHORTCUT_INVALID", "The specified shortcut is invalid."),
        Row(400, "SHORT_NAME_INVALID", "The specified short name is invalid."),
        Row(400, "SHORT_NAME_OCCUPIED", "The specified short name is already in use."),
        Row(400, "SLOTS_EMPTY", "The specified slot list is empty."),
        Row(400, "SLOWMODE_MULTI_MSGS_DISABLED", "Slowmode is enabled, you cannot forward multiple messages to this group."),
        Row(400, "SLUG_INVALID", "The specified invoice slug is invalid."),
        Row(400, "SMSJOB_ID_INVALID", "The specified job ID is invalid."),
        Row(400, "SMS_CODE_CREATE_FAILED", "An error occurred while creating the SMS code."),
        Row(400, "SRP_A_INVALID", "The specified inputCheckPasswordSRP.A value is invalid."),
        Row(400, "SRP_ID_INVALID", "Invalid SRP ID provided."),
        Row(400, "SRP_PASSWORD_CHANGED", "Password has changed."),
        Row(400, "STARGIFT_ALREADY_CONVERTED", "The specified star gift was already converted to Stars."),
        Row(400, "STARGIFT_ALREADY_REFUNDED", "The specified star gift was already refunded."),
        Row(400, "STARGIFT_ALREADY_UPGRADED", "The specified gift was already upgraded to a collectible gift."),
        Row(400, "STARGIFT_ATTRIBUTE_INVALID", "One of the specified star gift attributes is invalid."),
        Row(400, "STARGIFT_INVALID", "The passed gift is invalid."),
        Row(400, "STARGIFT_MESSAGE_INVALID", "The specified inputInvoiceStarGift.message is invalid."),
        Row(400, "STARGIFT_NOT_FOUND", "The specified gift was not found."),
        Row(400, "STARGIFT_NOT_OWNER", "You're not the owner of the gift you trying to transfer."),
        Row(400, "STARGIFT_NOT_UNIQUE", "You can't transfer a non-collectible gift."),
        Row(400, "STARGIFT_OBJECT_INVALID", "The specified star gift object is invalid."),
        Row(400, "STARGIFT_OFFER_INVALID", "The specified offer amount is invalid."),
        Row(400, "STARGIFT_OFFER_NOT_ALLOWED", "You can't send a purchase offer for this gift."),
        Row(400, "STARGIFT_OWNER_INVALID", "You cannot transfer or sell a gift owned by another user."),
        Row(400, "STARGIFT_PEER_INVALID", "The specified inputSavedStarGiftChat.peer is invalid."),
        Row(400, "STARGIFT_RESELL_CURRENCY_NOT_ALLOWED", "You can't buy the gift using the specified currency (i.e. trying to pay in Stars for TON gifts)."),
        Row(400, "STARGIFT_RESELL_TOO_EARLY_%d", "You will be able to resell this gift in %d seconds."),
        Row(400, "STARGIFT_SLUG_INVALID", "The specified gift slug is invalid."),
        Row(400, "STARGIFT_TRANSFER_TOO_EARLY_%d", "You cannot transfer this gift yet, wait %d seconds."),
        Row(400, "STARGIFT_UPGRADE_UNAVAILABLE", "A received gift can only be upgraded to a collectible gift if the [messageActionStarGift](https://core.telegram.org/constructor/messageActionStarGift)/[savedStarGift](https://core.telegram.org/constructor/savedStarGift).`can_upgrade` flag is set."),
        Row(400, "STARGIFT_USAGE_LIMITED", "The gift is sold out."),
        Row(400, "STARGIFT_USER_USAGE_LIMITED", "You've reached the starGift.limited_per_user limit, you can't buy any more gifts of this type."),
        Row(400, "STARREF_AWAITING_END", "The previous referral program was terminated less than 24 hours ago: further changes can be made after the date specified in userFull.starref_program.end_date."),
        Row(400, "STARREF_EXPIRED", "The specified referral link is invalid."),
        Row(400, "STARREF_HASH_REVOKED", "The specified affiliate link was already revoked."),
        Row(400, "STARREF_PERMILLE_INVALID", "The specified commission_permille is invalid: the minimum and maximum values for this parameter are contained in the [starref_min_commission_permille](https://core.telegram.org/api/config#starref-min-commission-permille) and [starref_max_commission_permille](https://core.telegram.org/api/config#starref-max-commission-permille) client configuration parameters."),
        Row(400, "STARREF_PERMILLE_TOO_LOW", "The specified commission_permille is too low: the minimum and maximum values for this parameter are contained in the [starref_min_commission_permille](https://core.telegram.org/api/config#starref-min-commission-permille) and [starref_max_commission_permille](https://core.telegram.org/api/config#starref-max-commission-permille) client configuration parameters."),
        Row(400, "STARS_AMOUNT_INVALID", "The specified amount in stars is invalid."),
        Row(400, "STARS_INVOICE_INVALID", "The specified Telegram Star invoice is invalid."),
        Row(400, "STARS_PAYMENT_REQUIRED", "To import this chat invite link, you must first [pay for the associated Telegram Star subscription &raquo;](https://core.telegram.org/api/subscriptions#channel-subscriptions)."),
        Row(400, "START_PARAM_EMPTY", "The start parameter is empty."),
        Row(400, "START_PARAM_INVALID", "Start parameter invalid."),
        Row(400, "START_PARAM_TOO_LONG", "Start parameter is too long."),
        Row(400, "STICKERPACK_STICKERS_TOO_MUCH", "There are too many stickers in this stickerpack, you can't add any more."),
        Row(400, "STICKERSET_INVALID", "The provided sticker set is invalid."),
        Row(400, "STICKERSET_NOT_MODIFIED", "The passed stickerset information is equal to the current information."),
        Row(400, "STICKERS_EMPTY", "No sticker provided."),
        Row(400, "STICKERS_TOO_MUCH", "There are too many stickers in this stickerpack, you can't add any more."),
        Row(400, "STICKER_DOCUMENT_INVALID", "The specified sticker document is invalid."),
        Row(400, "STICKER_EMOJI_INVALID", "Sticker emoji invalid."),
        Row(400, "STICKER_FILE_INVALID", "Sticker file invalid."),
        Row(400, "STICKER_GIF_DIMENSIONS", "The specified video sticker has invalid dimensions."),
        Row(400, "STICKER_ID_INVALID", "The provided sticker ID is invalid."),
        Row(400, "STICKER_INVALID", "The provided sticker is invalid."),
        Row(400, "STICKER_MIME_INVALID", "The specified sticker MIME type is invalid."),
        Row(400, "STICKER_PNG_DIMENSIONS", "Sticker png dimensions invalid."),
        Row(400, "STICKER_PNG_NOPNG", "One of the specified stickers is not a valid PNG file."),
        Row(400, "STICKER_TGS_NODOC", "You must send the animated sticker as a document."),
        Row(400, "STICKER_TGS_NOTGS", "Invalid TGS sticker provided."),
        Row(400, "STICKER_THUMB_PNG_NOPNG", "Incorrect stickerset thumb file provided, PNG / WEBP expected."),
        Row(400, "STICKER_THUMB_TGS_NOTGS", "Incorrect stickerset TGS thumb file provided."),
        Row(400, "STICKER_VIDEO_BIG", "The specified video sticker is too big."),
        Row(400, "STICKER_VIDEO_NODOC", "You must send the video sticker as a document."),
        Row(400, "STICKER_VIDEO_NOWEBM", "The specified video sticker is not in webm format."),
        Row(400, "STORIES_NEVER_CREATED", "This peer hasn't ever posted any stories."),
        Row(400, "STORIES_TOO_MUCH", "You have hit the maximum active stories limit as specified by the [`story_expiring_limit_*` client configuration parameters](https://core.telegram.org/api/config#story-expiring-limit-default): you should buy a [Premium](https://core.telegram.org/api/premium) subscription, delete an active story, or wait for the oldest story to expire."),
        Row(400, "STORY_ID_EMPTY", "You specified no story IDs."),
        Row(400, "STORY_ID_INVALID", "The specified story ID is invalid."),
        Row(400, "STORY_LIVE_ALREADY_%d", "This peer already has an active live story, and its ID is equal to %d."),
        Row(400, "STORY_NOT_MODIFIED", "The new story information you passed is equal to the previous story information, thus it wasn't modified."),
        Row(400, "STORY_PERIOD_INVALID", "The specified story period is invalid for this account."),
        Row(400, "STORY_SEND_FLOOD_MONTHLY_%d", "You've hit the monthly story limit as specified by the [`stories_sent_monthly_limit_*` client configuration parameters](https://core.telegram.org/api/config#stories-sent-monthly-limit-default): wait %d seconds before posting a new story."),
        Row(400, "STORY_SEND_FLOOD_WEEKLY_%d", "You've hit the weekly story limit as specified by the [`stories_sent_weekly_limit_*` client configuration parameters](https://core.telegram.org/api/config#stories-sent-weekly-limit-default): wait for %d seconds before posting a new story."),
        Row(400, "SUBSCRIPTION_EXPORT_MISSING", "You cannot send a [bot subscription invoice](https://core.telegram.org/api/subscriptions#bot-subscriptions) directly, you may only create invoice links using [payments.exportInvoice](https://core.telegram.org/method/payments.exportInvoice)."),
        Row(400, "SUBSCRIPTION_ID_INVALID", "The specified subscription_id is invalid."),
        Row(400, "SUBSCRIPTION_PERIOD_INVALID", "The specified subscription_pricing.period is invalid."),
        Row(400, "SUGGESTED_POST_AMOUNT_INVALID", "The specified price for the suggested post is invalid."),
        Row(400, "SUGGESTED_POST_PEER_INVALID", "You cannot send suggested posts to non-[monoforum](https://core.telegram.org/api/monoforum) peers."),
        Row(400, "SWITCH_PM_TEXT_EMPTY", "The switch_pm.text field was empty."),
        Row(400, "SWITCH_WEBVIEW_URL_INVALID", "The URL specified in switch_webview.url is invalid!"),
        Row(400, "TAKEOUT_INVALID", "The specified takeout ID is invalid."),
        Row(400, "TAKEOUT_REQUIRED", "A [takeout](https://core.telegram.org/api/takeout) session needs to be initialized first, [see here &raquo; for more info](https://core.telegram.org/api/takeout)."),
        Row(400, "TASK_ALREADY_EXISTS", "An email reset was already requested."),
        Row(400, "TEMP_AUTH_KEY_ALREADY_BOUND", "The passed temporary key is already bound to another **perm_auth_key_id**."),
        Row(400, "TEMP_AUTH_KEY_EMPTY", "No temporary auth key provided."),
        Row(400, "TERMS_URL_INVALID", "The specified [invoice](https://core.telegram.org/constructor/invoice).`terms_url` is invalid."),
        Row(400, "TEXTDRAFT_PEER_INVALID", "sendMessageTextDraftAction can only be used in private 1-on-1 chats."),
        Row(400, "THEME_FILE_INVALID", "Invalid theme file provided."),
        Row(400, "THEME_FORMAT_INVALID", "Invalid theme format provided."),
        Row(400, "THEME_INVALID", "Invalid theme provided."),
        Row(400, "THEME_MIME_INVALID", "The theme's MIME type is invalid."),
        Row(400, "THEME_PARAMS_INVALID", "The specified `theme_params` field is invalid."),
        Row(400, "THEME_SLUG_INVALID", "The specified theme slug is invalid."),
        Row(400, "THEME_TITLE_INVALID", "The specified theme title is invalid."),
        Row(400, "TIMEZONE_INVALID", "The specified timezone does not exist."),
        Row(400, "TITLE_INVALID", "The specified stickerpack title is invalid."),
        Row(400, "TMP_PASSWORD_DISABLED", "The temporary password is disabled."),
        Row(400, "TMP_PASSWORD_INVALID", "The passed tmp_password is invalid."),
        Row(400, "TODO_ITEMS_EMPTY", "A checklist was specified, but no [checklist items](https://core.telegram.org/api/todo) were passed."),
        Row(400, "TODO_ITEMS_TOO_MUCH", "You specified too many todo list items."),
        Row(400, "TODO_ITEM_DUPLICATE", "Duplicate [checklist items](https://core.telegram.org/api/todo) detected."),
        Row(400, "TODO_NOT_MODIFIED", "No todo items were specified, so no changes were made to the todo list."),
        Row(400, "TOKEN_EMPTY", "The specified token is empty."),
        Row(400, "TOKEN_INVALID", "The provided token is invalid."),
        Row(400, "TOKEN_TYPE_INVALID", "The specified token type is invalid."),
        Row(400, "TOPICS_EMPTY", "You specified no topic IDs."),
        Row(400, "TOPIC_CLOSED", "This topic was closed, you can't send messages to it anymore."),
        Row(400, "TOPIC_CLOSE_SEPARATELY", "The `close` flag cannot be provided together with any of the other flags."),
        Row(400, "TOPIC_DELETED", "The specified topic was deleted."),
        Row(400, "TOPIC_HIDE_SEPARATELY", "The `hide` flag cannot be provided together with any of the other flags."),
        Row(400, "TOPIC_ID_INVALID", "The specified topic ID is invalid."),
        Row(400, "TOPIC_NOT_MODIFIED", "The updated topic info is equal to the current topic info, nothing was changed."),
        Row(400, "TOPIC_TITLE_EMPTY", "The specified topic title is empty."),
        Row(400, "TO_ID_INVALID", "The specified `to_id` of the passed inputInvoiceStarGiftResale or inputInvoiceStarGiftTransfer is invalid."),
        Row(400, "TO_LANG_INVALID", "The specified destination language is invalid."),
        Row(400, "TRANSACTION_ID_INVALID", "The specified transaction ID is invalid."),
        Row(400, "TRANSCRIPTION_FAILED", "Audio transcription failed."),
        Row(400, "TRANSLATE_REQ_QUOTA_EXCEEDED", "Translation is currently unavailable due to a temporary server-side lack of resources."),
        Row(400, "TTL_DAYS_INVALID", "The provided TTL is invalid."),
        Row(400, "TTL_MEDIA_INVALID", "Invalid media Time To Live was provided."),
        Row(400, "TTL_PERIOD_INVALID", "The specified TTL period is invalid."),
        Row(400, "TYPES_EMPTY", "No top peer type was provided."),
        Row(400, "UNSUPPORTED", "`require_payment` cannot be *set* by users, only by monoforums: users must instead use the [inputPrivacyKeyNoPaidMessages](https://core.telegram.org/constructor/inputPrivacyKeyNoPaidMessages) privacy setting to remove a previously added exemption."),
        Row(400, "UNTIL_DATE_INVALID", "Invalid until date provided."),
        Row(400, "URL_EXPIRED", "The specified OAuth request has expired."),
        Row(400, "URL_INVALID", "Invalid URL provided."),
        Row(400, "USAGE_LIMIT_INVALID", "The specified usage limit is invalid."),
        Row(400, "USERNAMES_ACTIVE_TOO_MUCH", "The maximum number of active usernames was reached."),
        Row(400, "USERNAME_INVALID", "The provided username is not valid."),
        Row(400, "USERNAME_NOT_MODIFIED", "The username was not modified."),
        Row(400, "USERNAME_NOT_OCCUPIED", "The provided username is not occupied."),
        Row(400, "USERNAME_OCCUPIED", "The provided username is already occupied."),
        Row(400, "USERNAME_PURCHASE_AVAILABLE", "The specified username can be purchased on https://fragment.com."),
        Row(400, "USERNAME_SUFFIX_MISSING", "The required `bot` suffix is missing from the passed username."),
        Row(400, "USERPIC_UPLOAD_REQUIRED", "You must have a profile picture to publish your geolocation."),
        Row(400, "USERS_TOO_FEW", "Not enough users (to create a chat, for example)."),
        Row(400, "USERS_TOO_MUCH", "The maximum number of users has been exceeded (to create a chat, for example)."),
        Row(400, "USER_ADMIN_INVALID", "You're not an admin."),
        Row(400, "USER_ALREADY_INVITED", "You have already invited this user."),
        Row(400, "USER_ALREADY_PARTICIPANT", "The user is already in the group."),
        Row(400, "USER_BANNED_IN_CHANNEL", "You're banned from sending messages in supergroups/channels."),
        Row(400, "USER_BLOCKED", "User blocked."),
        Row(400, "USER_BOT", "Bots can only be admins in channels."),
        Row(400, "USER_BOT_INVALID", "User accounts must provide the `bot` method parameter when calling this method. If there is no such method parameter, this method can only be invoked by bot accounts."),
        Row(400, "USER_BOT_REQUIRED", "This method can only be called by a bot."),
        Row(400, "USER_BOT_TO_BOT_DISABLED", "Bot-to-bot messaging is disabled because one of the two bots hasn't enabled the Bot to Bot setting in @BotFather."),
        Row(400, "USER_CHANNELS_TOO_MUCH", "One of the users you tried to add is already in too many channels/supergroups."),
        Row(400, "USER_CREATOR", "For channels.editAdmin: you've tried to edit the admin rights of the owner, but you're not the owner; for channels.leaveChannel: you can't leave this channel, because you're its creator."),
        Row(400, "USER_GIFT_UNAVAILABLE", "Gifts are not available in the current region ([stars_gifts_enabled](https://core.telegram.org/api/config#stars-gifts-enabled) is equal to false)."),
        Row(400, "USER_ID_INVALID", "The provided user ID is invalid."),
        Row(400, "USER_INVALID", "Invalid user provided."),
        Row(400, "USER_IS_BLOCKED", "You were blocked by this user."),
        Row(400, "USER_IS_BOT", "Bots can't send messages to other bots."),
        Row(400, "USER_KICKED", "This user was kicked from this supergroup/channel."),
        Row(400, "USER_NOT_MUTUAL_CONTACT", "The provided user is not a mutual contact."),
        Row(400, "USER_NOT_PARTICIPANT", "You're not a member of this supergroup/channel."),
        Row(400, "USER_PUBLIC_MISSING", "Cannot generate a link to stories posted by a peer without a username."),
        Row(400, "USER_VOLUME_INVALID", "The specified user volume is invalid."),
        Row(400, "VENUE_ID_INVALID", "The specified venue ID is invalid."),
        Row(400, "VIDEO_CONTENT_TYPE_INVALID", "The video's content type is invalid."),
        Row(400, "VIDEO_DURATION_INVALID", "The duration of the specified video is invalid."),
        Row(400, "VIDEO_FILE_INVALID", "The specified video file is invalid."),
        Row(400, "VIDEO_PAUSE_FORBIDDEN", "You cannot pause the video stream."),
        Row(400, "VIDEO_STOP_FORBIDDEN", "You cannot stop the video stream."),
        Row(400, "VIDEO_TITLE_EMPTY", "The specified video title is empty."),
        Row(400, "VOICE_MESSAGES_FORBIDDEN", "This user's privacy settings forbid you from sending voice messages."),
        Row(400, "WALLPAPER_FILE_INVALID", "The specified wallpaper file is invalid."),
        Row(400, "WALLPAPER_INVALID", "The specified wallpaper is invalid."),
        Row(400, "WALLPAPER_MIME_INVALID", "The specified wallpaper MIME type is invalid."),
        Row(400, "WALLPAPER_NOT_FOUND", "The specified wallpaper could not be found."),
        Row(400, "WC_CONVERT_URL_INVALID", "WC convert URL invalid."),
        Row(400, "WEBAPP_REQ_ID_INVALID", "The specified webapp_req_id is invalid."),
        Row(400, "WEBAUTH_TOKEN_EXPIRED", "The specified auth token has expired."),
        Row(400, "WEBDOCUMENT_INVALID", "Invalid webdocument URL provided."),
        Row(400, "WEBDOCUMENT_MIME_INVALID", "Invalid webdocument mime type provided."),
        Row(400, "WEBDOCUMENT_SIZE_TOO_BIG", "Webdocument is too big!"),
        Row(400, "WEBDOCUMENT_URL_EMPTY", "The passed web document URL is empty."),
        Row(400, "WEBDOCUMENT_URL_INVALID", "The specified webdocument URL is invalid."),
        Row(400, "WEBPAGE_CURL_FAILED", "Failure while fetching the webpage with cURL."),
        Row(400, "WEBPAGE_MEDIA_EMPTY", "Webpage media empty."),
        Row(400, "WEBPAGE_NOT_FOUND", "A preview for the specified webpage `url` could not be generated."),
        Row(400, "WEBPAGE_URL_INVALID", "The specified webpage `url` is invalid."),
        Row(400, "WEBPUSH_AUTH_INVALID", "The specified web push authentication secret is invalid."),
        Row(400, "WEBPUSH_KEY_INVALID", "The specified web push elliptic curve Diffie-Hellman public key is invalid."),
        Row(400, "WEBPUSH_TOKEN_INVALID", "The specified web push token is invalid."),
        Row(400, "YOU_BLOCKED_USER", "You blocked this user."),
        Row(401, "AUTH_KEY_INVALID", "The specified auth key is invalid."),
        Row(401, "AUTH_KEY_PERM_EMPTY", "The method is unavailable for temporary authorization keys, not bound to a permanent authorization key."),
        Row(401, "AUTH_KEY_UNREGISTERED", "The specified authorization key is not registered in the system (for example, a PFS temporary key has expired)."),
        Row(401, "SESSION_EXPIRED", "The session has expired."),
        Row(401, "SESSION_PASSWORD_NEEDED", "2FA is enabled, use a password to login."),
        Row(401, "SESSION_REVOKED", "The session was revoked by the user."),
        Row(401, "USER_DEACTIVATED", "The current account was deleted by the user."),
        Row(401, "USER_DEACTIVATED_BAN", "The current account was deleted and banned by Telegram's antispam system."),
        Row(403, "ACCESS_DENIED", "The account was deactivated, or is a bot/service account."),
        Row(403, "ALLOW_PAYMENT_REQUIRED_%d", "This peer charges %d [Telegram Stars](https://core.telegram.org/api/stars) per message, but the `allow_paid_stars` was not set or its value is smaller than %d."),
        Row(403, "BOT_ACCESS_FORBIDDEN", "The specified method *can* be used over a [business connection](https://core.telegram.org/api/bots/connected-business-bots) for some operations, but the specified query attempted an operation that is not allowed over a business connection."),
        Row(403, "BOT_FORUM_CREATE_FORBIDDEN", "Since the bot's user.bot_forum_can_manage_topics flag is **not** set, the user cannot create or modify bot forum topics."),
        Row(403, "BOT_GUARD_NOT_SUPPORTED", "This bot is not designated as a \"join guard\" bot. This method is only available to bots that mediate user joins to chats. ."),
        Row(403, "BOT_VERIFIER_FORBIDDEN", "This bot cannot assign [verification icons](https://core.telegram.org/api/bots/verification)."),
        Row(403, "BROADCAST_FORBIDDEN", "Channel poll voters and reactions cannot be fetched to prevent deanonymization."),
        Row(403, "CHANNEL_PUBLIC_GROUP_NA", "channel/supergroup not available."),
        Row(403, "CHAT_ACTION_FORBIDDEN", "You cannot execute this action."),
        Row(403, "CHAT_ADMIN_INVITE_REQUIRED", "You do not have the rights to do this."),
        Row(403, "CHAT_ADMIN_REQUIRED", "You must be an admin in this chat to do this."),
        Row(403, "CHAT_FORBIDDEN", "This chat is not available to the current user."),
        Row(403, "CHAT_GUEST_SEND_FORBIDDEN", "You join the discussion group before commenting, see [here &raquo;](https://core.telegram.org/api/discussion#requiring-users-to-join-the-group) for more info."),
        Row(403, "CHAT_SEND_AUDIOS_FORBIDDEN", "You can't send audio messages in this chat."),
        Row(403, "CHAT_SEND_DOCS_FORBIDDEN", "You can't send documents in this chat."),
        Row(403, "CHAT_SEND_GAME_FORBIDDEN", "You can't send a game to this chat."),
        Row(403, "CHAT_SEND_GIFS_FORBIDDEN", "You can't send gifs in this chat."),
        Row(403, "CHAT_SEND_INLINE_FORBIDDEN", "You can't send inline messages in this group."),
        Row(403, "CHAT_SEND_MEDIA_FORBIDDEN", "You can't send media in this chat."),
        Row(403, "CHAT_SEND_PHOTOS_FORBIDDEN", "You can't send photos in this chat."),
        Row(403, "CHAT_SEND_PLAIN_FORBIDDEN", "You can't send non-media (text) messages in this chat."),
        Row(403, "CHAT_SEND_POLL_FORBIDDEN", "You can't send polls in this chat."),
        Row(403, "CHAT_SEND_ROUNDVIDEOS_FORBIDDEN", "You can't send round videos to this chat."),
        Row(403, "CHAT_SEND_STICKERS_FORBIDDEN", "You can't send stickers in this chat."),
        Row(403, "CHAT_SEND_VIDEOS_FORBIDDEN", "You can't send videos in this chat."),
        Row(403, "CHAT_SEND_VOICES_FORBIDDEN", "You can't send voice recordings in this chat."),
        Row(403, "CHAT_SEND_WEBPAGE_FORBIDDEN", "You can't send webpage previews to this chat."),
        Row(403, "CHAT_TYPE_INVALID", "The specified user type is invalid."),
        Row(403, "CHAT_WRITE_FORBIDDEN", "You can't write in this chat."),
        Row(403, "EDIT_BOT_INVITE_FORBIDDEN", "Normal users can't edit invites that were created by bots."),
        Row(403, "GROUPCALL_ALREADY_STARTED", "The groupcall has already started, you can join directly using [phone.joinGroupCall](https://core.telegram.org/method/phone.joinGroupCall)."),
        Row(403, "GROUPCALL_CHANGE_FORBIDDEN", "You cannot change this group call setting."),
        Row(403, "GROUPCALL_FORBIDDEN", "The specified group call cannot be used in this context."),
        Row(403, "INLINE_BOT_REQUIRED", "Only the inline bot can edit message."),
        Row(403, "MESSAGE_AUTHOR_REQUIRED", "Message author required."),
        Row(403, "MESSAGE_DELETE_FORBIDDEN", "You can't delete one of the messages you tried to delete, most likely because it is a service message."),
        Row(403, "NOT_ELIGIBLE", "The current user is not eligible to join the Peer-to-Peer Login Program."),
        Row(403, "PARTICIPANT_JOIN_MISSING", "Trying to enable a presentation, when the user hasn't joined the Video Chat with [phone.joinGroupCall](https://core.telegram.org/method/phone.joinGroupCall)."),
        Row(403, "PEER_ID_INVALID", "The provided peer id is invalid."),
        Row(403, "POLL_VOTE_REQUIRED", "Cast a vote in the poll before calling this method."),
        Row(403, "PREMIUM_ACCOUNT_REQUIRED", "A premium account is required to execute this action."),
        Row(403, "PRIVACY_PREMIUM_REQUIRED", "You need a [Telegram Premium subscription](https://core.telegram.org/api/premium) to send a message to this user."),
        Row(403, "PUBLIC_CHANNEL_MISSING", "You can only export group call invite links for public chats or channels."),
        Row(403, "RIGHT_FORBIDDEN", "Your admin rights do not allow you to do this."),
        Row(403, "SENSITIVE_CHANGE_FORBIDDEN", "You can't change your sensitive content settings."),
        Row(403, "TAKEOUT_REQUIRED", "A [takeout](https://core.telegram.org/api/takeout) session needs to be initialized first, [see here &raquo; for more info](https://core.telegram.org/api/takeout)."),
        Row(403, "USER_BANNED_IN_CHANNEL", "You're banned from sending messages in supergroups/channels."),
        Row(403, "USER_BOT_INVALID", "User accounts must provide the `bot` method parameter when calling this method. If there is no such method parameter, this method can only be invoked by bot accounts."),
        Row(403, "USER_CHANNELS_TOO_MUCH", "One of the users you tried to add is already in too many channels/supergroups."),
        Row(403, "USER_DELETED", "You can't send this secret message because the other participant deleted their account."),
        Row(403, "USER_DISALLOWED_STARGIFTS", "The recipient user has configured restrictions on which categories of star gifts they're willing to accept (unique, limited, or unlimited): the sender attempted to get a payment form for a gift that falls into a category the recipient has blocked."),
        Row(403, "USER_INVALID", "Invalid user provided."),
        Row(403, "USER_IS_BLOCKED", "You were blocked by this user."),
        Row(403, "USER_NOT_MUTUAL_CONTACT", "The provided user is not a mutual contact."),
        Row(403, "USER_NOT_PARTICIPANT", "You're not a member of this supergroup/channel."),
        Row(403, "USER_PERMISSION_DENIED", "The user hasn't granted or has revoked the bot's access to change their emoji status using [bots.toggleUserEmojiStatusPermission](https://core.telegram.org/method/bots.toggleUserEmojiStatusPermission)."),
        Row(403, "USER_PRIVACY_RESTRICTED", "The user's privacy settings do not allow you to do this."),
        Row(403, "USER_RESTRICTED", "You're spamreported, you can't create channels or chats."),
        Row(403, "VOICE_MESSAGES_FORBIDDEN", "This user's privacy settings forbid you from sending voice messages."),
        Row(403, "YOUR_PRIVACY_RESTRICTED", "You cannot fetch the read date of this message because you have disallowed other users to do so for *your* messages; to fix, allow other users to see *your* exact last online date OR purchase a [Telegram Premium](https://core.telegram.org/api/premium) subscription."),
        Row(404, "METHOD_INVALID", "The specified method is invalid."),
        Row(404, "PEER_ID_INVALID", "The provided peer id is invalid."),
        Row(406, "ALLOW_PAYMENT_REQUIRED", "This peer only accepts [paid messages &raquo;](https://core.telegram.org/api/paid-messages): this error is only emitted for older layers without paid messages support, so the client must be updated in order to use paid messages.  ."),
        Row(406, "API_GIFT_RESTRICTED_UPDATE_APP", "Please update the app to access the gift API."),
        Row(406, "AUTH_KEY_DUPLICATED", "Concurrent usage of the current session from multiple connections was detected, the current session was invalidated by the server for security reasons!"),
        Row(406, "BANNED_RIGHTS_INVALID", "You provided some invalid flags in the banned rights."),
        Row(406, "BUSINESS_ADDRESS_ACTIVE", "The user is currently advertising a [Business Location](https://core.telegram.org/api/business#location), the location may only be changed (or removed) using [account.updateBusinessLocation &raquo;](https://core.telegram.org/method/account.updateBusinessLocation).  ."),
        Row(406, "CALL_PROTOCOL_COMPAT_LAYER_INVALID", "The other side of the call does not support any of the VoIP protocols supported by the local client, as specified by the `protocol.layer` and `protocol.library_versions` fields."),
        Row(406, "CHANNEL_PRIVATE", "You haven't joined this channel/supergroup."),
        Row(406, "CHANNEL_TOO_LARGE", "Channel is too large to be deleted; this error is issued when trying to delete channels with more than 1000 members (subject to change)."),
        Row(406, "CHAT_FORWARDS_RESTRICTED", "You can't forward messages from a protected chat."),
        Row(406, "EDIT_MESSAGE_TEMP_RESTRICTED", "Message editing is temporarily forbidden for this user due to regulatory restrictions."),
        Row(406, "FILEREF_UPGRADE_NEEDED", "The client has to be updated in order to support [file references](https://core.telegram.org/api/file-references)."),
        Row(406, "FRESH_CHANGE_ADMINS_FORBIDDEN", "You were just elected admin, you can't add or modify other admins yet."),
        Row(406, "FRESH_CHANGE_PHONE_FORBIDDEN", "You can't change phone number right after logging in, please wait at least 24 hours."),
        Row(406, "FRESH_RESET_AUTHORISATION_FORBIDDEN", "You can't logout other sessions if less than 24 hours have passed since you logged on the current session."),
        Row(406, "INVITE_HASH_EXPIRED", "The invite link has expired."),
        Row(406, "PAYMENT_UNSUPPORTED", "A detailed description of the error will be received separately as described [here &raquo;](https://core.telegram.org/api/errors#406-not-acceptable)."),
        Row(406, "PEER_ID_INVALID", "The provided peer id is invalid."),
        Row(406, "PHONE_NUMBER_INVALID", "The phone number is invalid."),
        Row(406, "PHONE_PASSWORD_FLOOD", "You have tried logging in too many times."),
        Row(406, "POLL_COUNTRY_RESTRICTED", "Users from the current user's country cannot vote in this [country-restricted poll &raquo;](https://core.telegram.org/api/poll#country-restricted-polls)."),
        Row(406, "POLL_MEMBER_RESTRICTED", "Only channel subscribers can vote in this poll."),
        Row(406, "PRECHECKOUT_FAILED", "Precheckout failed, a detailed and localized description for the error will be emitted via an [updateServiceNotification as specified here &raquo;](https://core.telegram.org/api/errors#406-not-acceptable)."),
        Row(406, "PREMIUM_CURRENTLY_UNAVAILABLE", "You cannot currently purchase a Premium subscription."),
        Row(406, "PREVIOUS_CHAT_IMPORT_ACTIVE_WAIT_%dMIN", "Import for this chat is already in progress, wait %d minutes before starting a new one."),
        Row(406, "PRIVACY_PREMIUM_REQUIRED", "You need a [Telegram Premium subscription](https://core.telegram.org/api/premium) to send a message to this user."),
        Row(406, "SEND_CODE_UNAVAILABLE", "Returned when all available options for this type of number were already used (e.g. flash-call, then SMS, then this error might be returned to trigger a second resend)."),
        Row(406, "STARGIFT_EXPORT_IN_PROGRESS", "A gift export is in progress, a detailed and localized description for the error will be emitted via an [updateServiceNotification as specified here &raquo;](https://core.telegram.org/api/errors#406-not-acceptable)."),
        Row(406, "STARS_FORM_AMOUNT_MISMATCH", "The form amount has changed, please fetch the new form using [payments.getPaymentForm](https://core.telegram.org/method/payments.getPaymentForm) and restart the process."),
        Row(406, "STICKERSET_INVALID", "The provided sticker set is invalid."),
        Row(406, "STICKERSET_OWNER_ANONYMOUS", "Provided stickerset can't be installed as group stickerset to prevent admin deanonymization."),
        Row(406, "TOPIC_CLOSED", "This topic was closed, you can't send messages to it anymore."),
        Row(406, "TOPIC_DELETED", "The specified topic was deleted."),
        Row(406, "TRANSLATIONS_DISABLED", "Translations are unavailable, a detailed and localized description for the error will be emitted via an [updateServiceNotification as specified here &raquo;](https://core.telegram.org/api/errors#406-not-acceptable)."),
        Row(406, "UPDATE_APP_TO_LOGIN", "Please update your client to login."),
        Row(406, "USERPIC_PRIVACY_REQUIRED", "You need to disable privacy settings for your profile picture in order to make your geolocation public."),
        Row(406, "USERPIC_UPLOAD_REQUIRED", "You must have a profile picture to publish your geolocation."),
        Row(406, "USER_RESTRICTED", "You're spamreported, you can't create channels or chats."),
        Row(420, "2FA_CONFIRM_WAIT_%d", "Since this account is active and protected by a 2FA password, we will delete it in 1 week for security purposes. You can cancel this process at any time, you'll be able to reset your account in %d seconds."),
        Row(420, "ADDRESS_INVALID", "The specified geopoint address is invalid."),
        Row(420, "FLOOD_PREMIUM_WAIT_%d", "Please wait %d seconds before repeating the action, or purchase a [Telegram Premium subscription](https://core.telegram.org/api/premium) to remove this rate limit."),
        Row(420, "FLOOD_WAIT_%d", "Please wait %d seconds before repeating the action."),
        Row(420, "FROZEN_METHOD_INVALID", "The current account is [frozen](https://core.telegram.org/api/auth#frozen-accounts), and thus cannot execute the specified action."),
        Row(420, "PREMIUM_SUB_ACTIVE_UNTIL_%d", "You already have a premium subscription active until unixtime %d ."),
        Row(420, "SLOWMODE_WAIT_%d", "Slowmode is enabled in this chat: wait %d seconds before sending another message to this chat."),
        Row(420, "TAKEOUT_INIT_DELAY_%d", "Sorry, for security reasons, you will be able to begin downloading your data in %d seconds. We have notified all your devices about the export request to make sure it's authorized and to give you time to react if it's not."),
        Row(500, "AICOMPOSE_TIMEOUT", "A timeout occurred while composing the message."),
        Row(500, "AUTH_KEY_UNSYNCHRONIZED", "Internal error, please repeat the method call."),
        Row(500, "AUTH_RESTART", "Restart the authorization process."),
        Row(500, "AUTH_RESTART_%d", "Internal error (debug info %d), please repeat the method call."),
        Row(500, "CALL_OCCUPY_FAILED", "The call failed because the user is already making another call."),
        Row(500, "CDN_UPLOAD_TIMEOUT", "A server-side timeout occurred while reuploading the file to the CDN DC."),
        Row(500, "CHAT_ID_GENERATE_FAILED", "Failure while generating the chat ID."),
        Row(500, "CHAT_INVALID", "Invalid chat."),
        Row(500, "MSG_WAIT_FAILED", "A waiting call returned an error."),
        Row(500, "OAUTH_REQUEST_INVALID", "The specified OAuth request is invalid."),
        Row(500, "PERSISTENT_TIMESTAMP_OUTDATED", "Channel internal replication issues, try again later (treat this like an RPC_CALL_FAIL)."),
        Row(500, "RANDOM_ID_DUPLICATE", "You provided a random ID that was already used."),
        Row(500, "SEND_MEDIA_INVALID", "The specified media is invalid."),
        Row(500, "SIGN_IN_FAILED", "Failure while signing in."),
        Row(500, "TRANSLATE_REQ_FAILED", "Translation failed, please try again later."),
        Row(500, "TRANSLATION_TIMEOUT", "A timeout occurred while translating the specified text."),
    )

    data class Row(val httpCode: Int, val pattern: String, val description: String)
}
