org.monogram.domain.models.MessageModel
org.monogram.domain.models.MessageReactionModel
org.monogram.domain.models.ForwardInfo
org.monogram.domain.models.MessageSendingState
org.monogram.domain.models.MessageEntity
org.monogram.domain.models.MessageEntityType
org.monogram.domain.models.WallpaperModel
org.monogram.domain.models.StickerSetModel
org.monogram.domain.models.TopicModel
org.monogram.domain.models.AttachMenuBotModel
org.monogram.domain.models.InlineBotResultsModel
org.monogram.domain.models.MessageContent
