name: Build APKs for Android using Nix

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v31

    - name: Add required files
      run: |
        echo "${{ secrets.LOCAL_PROPERTIES }}" >local.properties
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" >app/google-services.json

    - name: Build Task
      run: nix --experimental-features "nix-command flakes" run .#buildRelease
    
    - name: Upload Release APKs
      uses: actions/upload-artifact@v7
      with:
        name: Release APKs
        path: app/build/outputs/apk/release/*.apk

